### ISSUE TITLE
[mini-project]- Gonzalo Alvarez

### ISSUE THREAD

**Issue by gonalvarez05** [ironhack-datalabs/datamad1020#106]
Holaa! Ya tengo el primer project! Tengo que mejorar el readme para los próximos projects que veo que cuando lo abres de forma predeterminada esta un poco desordenado.

https://github.com/gonalvarez05/mini-project

**Comment by WHYTEWYLL** [comment]
Hola Gonzalo!!! 🤠 

DIOS, PRIMER PROYECTO!!! Que ilusión no? Si echas la vista atrás, mira lo que has conseguido en solo una semana. En cuanto a corrección, y cosas a tener en cuenta. Poquito te tengo que decir, porque ya fue todo dicho durante tu presentación. Y lo tienes en mente, que para el de esta semana. Se convierta en una realidad! 🚀 


![5d7](https://user-images.githubusercontent.com/49686519/97298975-83a6d380-1854-11eb-9bce-ad41f01e35f4.png)
