### ISSUE TITLE
[mini-project] Ignacio Ordovás Pascual

### ISSUE THREAD

**Issue by ordovas** [ironhack-datalabs/datamad1020#107]
Hola! He escogido el juego del ahorcado:

https://github.com/nachordo/mini-project.git

Saludos

![](https://i.kym-cdn.com/entries/icons/original/000/027/763/07B89120-B48D-45FB-AF1D-49AF6CD16790.jpeg)

**Comment by adrianacoca** [comment]
Buenas tardes Nacho!

Primero de todo te quiero felicitar por tu proyecto, lo has hecho increíble y desde luego que has intentado ir un paso mas allá. 👏 
Cosas que me ha gustado mucho ver en tu proyecto:
 - El README explica tu proyecto de manera muy clara, así como los comentarios del texto✅ 
 - Crear una estructura de carpetas muy ordenada ✅ 
 - Importar funciones de otros archivos ✅ 
 - Crear varios niveles ✅ 
 - Crear varias categorías para el juego involucrando al jugador con la opción de añadir categorías ✅ 
(esto mola mucho en programación porque las colaboraciones entre programadores son super comunes) 
 - Has usado programación defensiva para asegurarte de que los inputs son validos ✅ 

Enhorabuena! 🚀 

![images](https://user-images.githubusercontent.com/65229646/97312840-37fd2580-1866-11eb-94d7-1daae20e808d.png)
