### ISSUE TITLE
[mini-project] Blanca de Ochoa

### ISSUE THREAD

**Issue by BlancadeOchoa** [ironhack-datalabs/datamad1020#110]
Me ha parecido muy divertido el proceso de diseñar un juego desde cero!!

Es verdad que al ser un juego tan conocido he podido aprender muchisimo del codigo que han escrito otras personas en internet y coger ideas que me han parecido interesantes para aplicarlas en mi juego y hacerlo de alguna manera más mio.

He aprendido muchisimo, gracias! 

https://github.com/BlancadeOchoa/mini-project.git

**Comment by WHYTEWYLL** [comment]
Hola Blanca! ✋ 

Me hace ilusión, que te emocione tanto. En verdad, es para ello. Piensa que solo han pasado 5 días, y has hecho un juego SOLA. Además como tu bien dices, uno bien conocido! Esa justa esa, es la magia de la que se basa este mundo. Entender código de otros, coger ideas, aportar y mejorar. En eso se basa! APRENDER! En cuanto a cosas que decirte, poco te voy a comentar. Ya que te dimos feedback, cuando presentaste. Felicitarte por ese Readme, esa buena` def main` y sobre todo por coger ideas y entenderlo que es lo importante. Sigue asi!! 🚀 


![5d8cd88d1478a](https://user-images.githubusercontent.com/49686519/97294577-74bd2280-184e-11eb-8cbc-23e511708e90.jpg)
