### ISSUE TITLE
[mini-project] Candela Garcia

### ISSUE THREAD

**Issue by canbot92** [ironhack-datalabs/datamad1020#111]
https://github.com/candelagarciafdez/mini-project-hangman.git

**Comment by adrianacoca** [comment]
Buenos días Candela!

Tu proyecto del ahorcado está muy bien, has conseguido que el juego funcione y encima con dibujitos!! Me gusta mucho ver que para esto lo has importado de otro archivo. 🤩  
Como has dicho habría estado guay que se pudiese ver las letras que ya has dicho y pedir otra si se están repitiendo. Otra cosa que podrías haber incluido es que la consola preguntase si quieres volver a jugar. 
En cuanto a la presentación del proyecto, el readme y los comentarios son super útiles para entender el código. Me gustaría que intentaras organizar los archivos de manera más modular para futuros proyectos (ej importando funciones). 
Dicho esto enhorabuena por el proyecto! 🚀 

![images](https://user-images.githubusercontent.com/65229646/97304119-9a9cf400-185b-11eb-8d02-e34fb52481ae.png)
