### ISSUE TITLE
[mini-project] Borja del Río

### ISSUE THREAD

**Issue by BorjaRio** [ironhack-datalabs/datamad1020#112]
https://github.com/BorjaRio/Mini-project/blob/main/juegos.py

ahi va el juego ! he elegido el juego Guess The Number

:) 
![image](https://user-images.githubusercontent.com/70910001/97117524-9c07d880-1704-11eb-8d7f-29cdbb22bdef.png)

**Comment by WHYTEWYLL** [comment]
Hola Borja!!

Que tal tío? Quien lo diría eh! En 5 días, y ya TU primer juego!!  Felicidades tio! Im proud! 

Cositas que decirte, que imagino que tomaste nota de los otros compis que presentaron. Tanto este juego como los otros. Los readmes, dales un poco de cuerpo. Es lo atractivo no? Por ejemplo podrías poner esta imagen en ese readme e incitar a que entre 😉 .

Las funciones, este proyecto iba de usar funciones. De crearlas , llamarlas e importarlas si buscamos esa modularidad , escribiéndolas en otros archivos. Cosa que no esta, y era una de las claves de este proyecto. Funciona, si que es importante. Pero para la próxima, y que sirva de aquí en adelante : seguir los obligatorios de los proyectos , que esta todo descrito en los readmes de los proyectos y en caso de no estar claro algo, pregunte caballero. Pero los obligatorios hay que cubrirlos.

Pero bueno, estoy feliz y tu deberías estarlo también. Felicidades por ese primer proyecto. Sigue asi! 🚀 

![5d7](https://user-images.githubusercontent.com/49686519/97296431-f2822d80-1850-11eb-9e62-33eefda74582.png)
