### ISSUE TITLE
[mini-project] Alba Álvaro

### ISSUE THREAD

**Issue by AlbaAlvaro** [ironhack-datalabs/datamad1020#113]
https://github.com/AlbaAlvaro/mini-project.git

**Comment by WHYTEWYLL** [comment]
Hola Alba!!! 🧗‍♀️ 

Que tal estas? 😄 Que tal fue esa aventura, sola ante el peligro de este primer proyecto? Antes de nada felicitarte por esa primera aventura en solitario! 💪 

En cuanto al proyecto, que te puedo decir? Bueno , por parte el Readme me gusta mucho, pero puedes añadir alguna imagen o jugar un poco con el MarkDown para que quede un poquito mas animado, pero sin pasarnos que no somos diseñadores, aunque si quieres es un plus con el resto. En cuanto al código, FUNCIONA! Asi que 💯 ! Has usado funciones 👌  Que es lo que buscábamos en este primer proyecto, pero si te das cuenta tanto la funciones de `win_player` como `win_computer` , son muy parecidas no? No podrías como crear una sola, y que en función de un parámetro, imprima O o X. y en cuanto a los if, alguna reestructuración se puede hace para no tener que hacer tantos. Pero eso son cosas, de tu yo futuro. Simplemente te las menciono para que lo tengas en cuento. 

FELICIDADES! ESTA MUY BIEN! Sigue asi! 🚀 


![playing-tic-tac-toe-fact-44007434](https://user-images.githubusercontent.com/49686519/97298222-6cb3b180-1853-11eb-88cd-b498cc89734b.png)
