### ISSUE TITLE
[mini-project] Angela Gomez

### ISSUE THREAD

**Issue by angelagomezf** [ironhack-datalabs/datamad1020#117]
https://github.com/angelagomezf/Mini-project

**Comment by WHYTEWYLL** [comment]
Hola , Angela!! 🤠 

Que tal fue este primer proyecto? Esta aventura, en solitario a la que le dedicaste todo el finde semana jeje. Jokes aside, el juego funciona! Congratulations!! Pero cositas a tener en cuenta:

-Si que es cierto que has creado una función , pero yo creo que podrías dividir tu código en un par de funciones, para buscar esa modularidad de la que hablábamos. No? 

- Por otro lado, ese Readme? Esta mas vacío que los comentarios de esta Issue 🤣 .

- Me gusta mucho, esa idea de usar **time** para dar la sensacion de que esta escribiendo el programa. Good point!

De cualquier forma, el proyecto esta muy bien!! FELICIDADES!! 🎊  

![5d8cd88d1478a](https://user-images.githubusercontent.com/49686519/97300250-7db1f200-1856-11eb-85aa-352ebdf512e0.jpg)
