### ISSUE TITLE
[mini-project] Gerardo Vitale

### ISSUE THREAD

**Issue by gerardovitale** [ironhack-datalabs/datamad1020#123]
https://github.com/gerardovitale/strong-random-password-generator.git

**Comment by WHYTEWYLL** [comment]
Hola Gerar!!! 🤠 

Que tal estas? Como fue esta primera aventura solo ante el peligro? Primero de todo, felicitarle por ese primer proyecto individual, realizado con éxito. FUNCIONAL! Como tiene que ser, si señor! Muy bien ese Readme, por si no lo sabias se pueden añadir imágenes y mas cositas, investiga un poco sobre Markdown 🥳 . En cuanto al código, los objetivos de modularidad y de crear y funciones. Mas que cumplidos! 👍  y además funciona así que esta redondo! Además ya ese test, es la guinda.

Una recomendaciones, en cuanto a la organización. Si investigas otros repositorios, y bueno también se comento en clase, un archivo main.py , al ver este archivos todos sabemos que es ese el primero que tenemos que ejecutar. En tu caso, tendríamos que abrir todo, y darnos cuenta. En verdad muchos de esos archivos lo podríamos guardar dentro de una carpta "src" source , y dejar únicamente afuera ese readme y main.py. Quedando todo mas claro no? Pero son cositas, para que las tengas en cuenta de cara al futuro.

Además siempre esta bien el comentario las funciones, explicando que hace cada una de ellas conceptualmente. Para ayudar a esa persona que lo va a usar o esta leyendo a entenderlo mejor.

Poquito mas que decirte señor. Muy buen trabajo! Sigue así ! 🚀 

![5dcaf592d5975](https://user-images.githubusercontent.com/49686519/97307686-4d6f5100-1860-11eb-9328-12aae9894ba3.jpg)
