### ISSUE TITLE
[mini-proyect] Adrian Madrid

### ISSUE THREAD

**Issue by Adrian96119** [ironhack-datalabs/datamad1020#124]

**Comment by WHYTEWYLL** [comment]
Hola Adri!!! 🤠

Como estas, Titan? Como fue esta primera aventura solo ante el peligro? Primero de todo, felicitarle por ese primer proyecto individual, realizado con éxito. FUNCIONAL! Como tiene que ser, si señor! Muy bien ese Readme, por si no lo sabias se pueden añadir imágenes y mas cositas, investiga un poco sobre Markdown 🥳 . En cuanto al código, los objetivos de modularidad y de crear y funciones. Mas que cumplidos! 👍 y además funciona así que esta redondo! Además ya ese test, es la guinda.

Una recomendaciones, en cuanto a la organización. Si investigas otros repositorios, y bueno también se comento en clase, un archivo main.py, que en tu caso es el de juegocompleto, pero como que `main.py` es mas pro xD  , al ver este archivos todos sabemos que es ese el primero que tenemos que ejecutar. En verdad muchos de esos archivos lo podríamos guardar dentro de una carpta "src" source , y dejar únicamente afuera ese readme y main.py. Quedando todo mas claro no? Pero son cositas, para que las tengas en cuenta de cara al futuro.

Además como tú muy bien has hecho , siempre esta bien el comentar las funciones, explicando que hace cada una de ellas conceptualmente. Para ayudar a esa persona que lo va a usar o esta leyendo a entenderlo mejor. Good Job! 👍 

Poquito mas que decirte señor. Muy buen trabajo! Sigue así ! 🚀

![5d8cd88d1478a](https://user-images.githubusercontent.com/49686519/97321252-f6bd4380-186e-11eb-9097-5e3da7b78540.jpeg)


P.d: la próxima vez ponme el url del repositorio , en el issue 😉 .
