### ISSUE TITLE
[mini-project] Edu Oporto

### ISSUE THREAD

**Issue by EduOporto** [ironhack-datalabs/datamad1020#127]
https://github.com/EduOporto/ironhack-projects/tree/main/blackjack

Ahí va mi proyecto. Es el juego del blackjack. Me ha resultado muy complicado hacer la función para definir el comportamiento del dealer cuando tiene que completar su mano, me ha salido una función bastante larga. Si tengo algo de tiempo esta semana entre lab y lab me gustaría limpiar un poco el documento de las funciones.

**Comment by adrianacoca** [comment]
Buenas tardes Edu, 

Valiente con el black jack! 

Te mando un par de comentarios sobre la entrega:
- Increible el README te lo has currado un montón 🤩  ! Me parece super útil la forma en la que has ido explicando los archivos y funciones que has ido creando y lo que hace cada una. 
- También son muy útiles los comentarios que has puesto a lo largo del código
- Me gusta ver que has puesto en practica las generators functions con la función dealer
- Has conseguido lidiar con los As de tal manera que  obtenga el valor de 1 o 11

Dicho esto, podrías haber hecho que preguntase si quieres volver a ejecutar el código (poniéndonos muuuy exquisitos...)
Enhorabuena por el trabajo, está de diez! 🚀

**Comment by EduOporto** [comment]
Muchas gracias por el feedback!!! Lo del As para el dealer casi me vuelve
loco! Lo dejo en standby, porque no me gusta que sea tan larga la función,
espero que al final del bootcamp pueda reducirlo más. Y lo de que sea
recursivo más que nada que me quedé sin tiempo, pero hubiese sido fácil
hacerlo, lo pensé...
