### ISSUE TITLE
[mini-project] Carlos Vila-San Juan

### ISSUE THREAD

**Issue by carlosvilasanjuan** [ironhack-datalabs/datamad1020#130]
-  Ejecuta en Notebook pero no en terminal, 
-  He tenido que simplificar la funcion de CPU Selection para reducir fallos

**Comment by carlosvilasanjuan** [comment]
link: https://github.com/carlosvilasanjuan/ironhack_projects
- tip tap toe notebook se refiere a la version desarrollada en notebook
- el resto se refire a los diferentes modulos de vsc

**Comment by WHYTEWYLL** [comment]
Hola Carlos! 😄 

Vamos por partes!! En primer lugar , felicidades caballero, por pasar por esta aventura tú solito. En cuanto a los objetivos del proyecto era hacer funcionar uno de los juegos, usando funciones en un ".py" . El GitHub, es un poquito un caos tienes varios archivos, que están varios. Si te funciona en jupyter, te tiene que funcionar en visual. El hecho por el que no te funciona, son por errores de importación de las diferentes funciones y parámetros a las funciones.

El Readme, es una parte importante por si no lo sabias se pueden añadir imágenes y mas cositas, investiga un poco sobre Markdown 🥳 . 

Una recomendaciones, en cuanto a la organización. Si investigas otros repositorios, y bueno también se comento en clase, un archivo main.py , al ver este archivos todos sabemos que es ese el primero que tenemos que ejecutar. En tu caso, tendríamos que abrir todo, y darnos cuenta. En verdad muchos de esos archivos lo podríamos guardar dentro de una carpta "src" source , y dejar únicamente afuera ese readme y main.py. Quedando todo mas claro no? Pero son cositas, para que las tengas en cuenta de cara al futuro.

Además siempre esta bien el comentario las funciones, explicando que hace cada una de ellas conceptualmente. Para ayudar a esa persona que lo va a usar o esta leyendo a entenderlo mejor.

De todos modos, esta bien! Para un primer proyecto! Para los siguiente, vamos a por menos seguro y de ahi a mas. PERO CUMPLIENDO LO REQUISITOS!! Sigue así! 🚀 Hacia arriba! ⭐ 

![5f470a4fa0296](https://user-images.githubusercontent.com/49686519/97325515-603f5100-1873-11eb-954a-8e6748c042ba.jpeg)
