### ISSUE TITLE
[mini-project] Alberto Jiménez

### ISSUE THREAD

**Issue by Albertojd** [ironhack-datalabs/datamad1020#131]
LINK: https://github.com/Albertojd/Mini-project/tree/hanged

Perdonad, creía no había hecho bien la Issue

**Comment by WHYTEWYLL** [comment]
Hola Alberto!! 😄 

Don't worry!! Está, todo bien!

Vamos por partes, hay cositas que me gustan muchos y otras hay que dar un apunte sobre ella. Por un lado, antes de nada, te felicito por haberte embarcado en esta primera aventura en solitario, y sobrevivir! Muy bien con ese readme!! Siempre quedan mejor con alguna imagen, se pueden conseguir muchas cosas. Investiga un poco sobre Markdown! Es un pequeño mundo.

En cuanto a los objetivos del trabajo, están mas que conseguido! El juego tiene vida  y ademas has creado y utilizado funciones. ✅  Aunque si que es verdad que podríamos usarlas para dejar el código mas limpio, por ejemplo los cuerpos en otro archivo ...

Una recomendaciones, en cuanto a la organización. Si investigas otros repositorios, y bueno también se comento en clase, un archivo main.py , al ver este archivos todos sabemos que es ese el primero que tenemos que ejecutar. En tu caso, tendríamos que abrir todo, y darnos cuenta. En verdad muchos de esos archivos lo podríamos guardar dentro de una carpta "src" source , y dejar únicamente afuera ese readme y main.py. Quedando todo mas claro no? Pero son cositas, para que las tengas en cuenta de cara al futuro.

Aun así, muy buen trabajo! Esta genial! Sigue así!! 🚀 

![5d8cd88d1478a](https://user-images.githubusercontent.com/49686519/97323355-02aa0500-1871-11eb-8c6d-c1fcc99698df.jpeg)
