### ISSUE TITLE
[mini-project] Isa Searle Riesgo

### ISSUE THREAD

**Issue by isabel-searle** [ironhack-datalabs/datamad1020#132]
https://github.com/isabel-searle/mini-project

**Comment by isabel-searle** [comment]
https://github.com/isabel-searle/mini-project

**Comment by adrianacoca** [comment]
Buenas tardes Isa, 

Me alegra ver que has completado el README de tu proyecto, no obstante me gustaría que entrases en un poco más de detalle sobre el proyecto para futuros trabajos. También podrías mencionar cosas como: que podría haber hecho para mejorar el proyecto si hubiese tenido más tiempo, como he organizado la estructura del proyecto, cosas que ayudan a entender los pasos que has seguido. 

En cuanto a el proyecto en sí, como mencionamos en clase habría estado bien que hubieses organizado las funciones en archivos distintos para tener una estructura más organizada. 

Dicho esto estoy muy contenta con el trabajo! 
Has intentado ir más allá en algunos aspectos como por ejemplo:
 - programación defensiva mediante el try y except ✅  
 - porcentaje de success rate (muy creativa) ✅  
 - dar la posibilidad de volver a jugar al juego una vez llegado a su fin ✅  

![unnamed](https://user-images.githubusercontent.com/65229646/97327272-21aa9600-1875-11eb-8c72-444fa2f5e3f2.png)
