### ISSUE TITLE
[mini-project] Gonzalo Arroyo

### ISSUE THREAD

**Issue by Gon41** [ironhack-datalabs/datamad1020#134]
https://github.com/Gon41/-mini-proyect-

El proyecto me ha parecido muy chulo.

He tenido dificultades a la hora de hacer jugar a la máquina estableciendo un patrón para que ella juegue racionalmente.

**Comment by adrianacoca** [comment]
Buenas tardes Gon!

Me alregra muucho ver que le has dado otra vuelta al proyecto después de la clase de ayer 👏  🚀 
El README está bien! Para el futuro podrías añadirle un poco más de información como 
- Estructura del proyecto (distintos ficheros y funciones)
- Cosas que habrías hecho si hubieras tenido mas tiempo 

Sobre la parte en la que la maquina juega sola: 
```
if numero_maquina > numero_ordenador:
    numero_maquina2 = random.randit(numero_maquina,21)
    print(numero_maquina2)
```
Este statement se ocupa de imprimir el nuevo numero que elige la máquina, no obstante te falta un if statement que elija un numero dado que `numero_maquina < numero_ordenador` igual que el que has hecho dade que el `numero_maquina > numero_ordenador`. 
Para que la maquina juegue recursivamente, al bucle `while contador < 5:` deberías haberle añadido `numero_maquina != numero_ordenador`

Si quieres que juegue raciónalmente podrías hacer algo como elegir el numero que sea la media del rango (dependiendo si el número es mayor o menor) de tal manera que sería algo parecido a esto: 
```
numero_maquina = numero_ordenador/2
if numero_maquina < numero_ordenador:
    numero_maquina=numero_maquina/2
elif numero_maquina > numero_ordenador:
    numero_maquina=numero_maquina*3/2
```

Enhorabuena por tu trabajo, se nota que te lo has currado 🚀
