### ISSUE TITLE
[mini-project] Clayton Louden

### ISSUE THREAD

**Issue by WyattGwyon** [ironhack-datalabs/datamad1020#135]
https://github.com/WyattGwyon/Mini-project

**Comment by adrianacoca** [comment]
Buenas tardes Clayon, 

Te comento un par de cosas sobre tu proyecto del finde:
 - En primer lugar, cuando trabajes en repos que hayas creado tú en los que nadie más va a trabajar, no es necesario que crees otra rama (por lo tanto es algo que no tendrás que hacer para los proyectos). Dicho esto, es muy útil hacer esto a la hora de trabajar en un proyecto junto con otros programadores. 
- Cuando tienes una estructura de ficheros compleja, es muy útil que la expliques un poco en el README para poder entender la organización del proyecto. 
- Como dijimos en clase igual has intentado hacer el juego demasiado complejo a la primera. Por ejemplo, lo de realizar apuestas era algo que podrías haber hecho una vez asegurado que el juego funciona. 
- Una forma muy guay que podrías haber usado para sacar cartas de la baraja es creando una lista con todas las cartas, barajándolas con la función shuffle (de la librería random) y usando una función generadora que fuese cogiendo de carta en carta. (No obstante la forma en la que lo has hecho tú también está bien, sólo te doy ideas para futuros proyectos)
Dicho esto, soy consciente de que has escogido un juego mucho más complicado que algunos de los otros alumnos y te lo has trabajado un montón. A pesar de que el juego no funcione del todo, deberías estar orgulloso por el trabajo que has hecho. Has creado funciones y las has importado a otros archivos ✅ , has creado un README que está bastante bien ✅ y creo que generalmente has comprendido los conceptos que vimos durante la semana. 
Enhorabuena 👏 👏 👏
