### ISSUE TITLE
[mini-project] Alejandro Medina

### ISSUE THREAD

**Issue by medinaale91** [ironhack-datalabs/datamad1020#205]
https://github.com/medinaale91/Mini-project

**Comment by adrianacoca** [comment]
Buenos días Ale!!

Las correcciones de este proyecto llegan un poco tarde pero bueno... 🙈 
Por lo general tu proyecto está super bien, te comento un par de cosas:
 - Veo que has usado funciones para ejecutar el juego y esto era el principal objetivo del juego ✅ . Como comentamos en clase, una manera más ordenada de hacer esto sería separando las funciones en distintos archivos e importándolas. Por lo tanto sólo tendrías la función game en el archivo main. 
 - En cuanto a las funciones que has creado, creo que queda muy claro lo que hace cada función y como se relacionan entre ellas. 
 - Has usado programación defensiva para asegurarte de que el input sea una letra (teniendo en cuenta las mayúsculas y minúsculas) 🤩 
 - Algunas cosas que se me ocurren que podrías haber añadido son las siguientes: Preguntar si quiere jugar de nuevo una vez acabada la partida. También podrías haberle dado a elegir al jugador entre varias listas de palabras.

Enhorabuena por el trabajo! 🚀 🚀 🚀 🚀  

![mages](https://user-images.githubusercontent.com/65229646/97974463-eace0600-1dc7-11eb-8a8e-c01abbce67ee.png)
