### ISSUE TITLE
[sharks-project] Cristina Arenas Izquierdo

### ISSUE THREAD

**Issue by crisarenas** [ironhack-datalabs/datamad1020#214]
https://github.com/crisarenas/W2-Data-Sharks

**Comment by WHYTEWYLL** [comment]
Buenos dias, Criss!!!!! 😄 

FELICIDADES!!! Llegaste a la isla!! En cuanto al proyecto he de decirte que esta suuuuper bien eh! A pesar de que no sea el resultado final que estábamos buscando. Aun asi, hemos llegado y muy bien. De verdad! 

Te comento algunas cosillas para futuros viajes, okey? 

- Muy bien separando, análisis y cleaning . Nos da muchísimo mas de juego, y organización. Y eso es importante!

- **Limpieza**: estoy muy bien,  has seguidos pasos correctos y bien justificados. Aunque en los procesos de limpieza de cada columna, se abusa demasiado de los if else, elif . No es problema y es normal al principio, y funciona so 👍  . Pero si utilizamos un diccionario o lista podemos pasar de 10 líneas muy parecidas, a muchas menos . Lo que hemos comentado, durante la corrección del resto de proyectos.

- **Análisis** Considero que esta muy  claro, si que hubiese esta bien, experimental con otro tipos de graficos. Por el simple hecho de probar y descubrir. Pero esta suuper bien!!

No me enrollo mas, seguimos en el barco. Pase lo que pase, y llegaremos, ya habrá tiempo de dejar las cosas como nos gustaría. No preocuparse. Sigue así ! 🚀 P.d: Cualquier cosita me dices <3 !

![images](https://user-images.githubusercontent.com/49686519/97979903-3e445200-1dd0-11eb-8093-e59544e59f9f.jpg)
