### ISSUE TITLE
[data-cleaning-sharks] Candela García 

### ISSUE THREAD

**Issue by canbot92** [ironhack-datalabs/datamad1020#215]
https://github.com/candelagarciafdez/data-cleaning-sharks.git

**Comment by adrianacoca** [comment]
Buenos días Candela, 

Tu proyecto de pandas 🐼 está suuuper bien. Veo que ya vas cogiendole el tranquillo a la sintaxis de pandas 🚀

Te comento un par de cosas que me han gustado y otras que podrías mejorar:
- Has organizado la limpieza de datos y el análisis en distintos jupyters 👌 
- Has limpiado los nombres de las columnas mediante el strip, lower y replace ✅ 
- Has mirado el nombre de datos validos por columna (super útil para entender la base de datos con la que estamos trabajando)
- Has creado una columna para los meses del año 🙌 
- Has creado la columna hemisferio mediante el país - utilizando los datos para extraer información nueva (estrategia muy útil para sacarle más partido a los datos) 🔥 
- Has plotteado gráficos usando los datos de varias columnas para llegar a conclusiones 👍  
- En cuanto al README, procura hacerlo más detallado. Como por ejemplo mencionar que columnas te han sido más o menos útiles, cómo las has ultilizado. Veo que has sacado gráficos y conclusiones bastante interesantes en el jupyter, podrías haberlos puesto en el readme también.
- Has dropeado las filas con missing values con `df.dropna(inplace = True)`. Hay una manera de dropear las filas sólo si tienen un mínimo de missing values mediante el threshold. Ej: `df.dropna(inplace = True, thresh=5)` --> eliminar la fila sólo si hay 5 o más missing values. De esta manera evitamos cargarnos muchas filas que pueden sernos útiles. 

Enhorabuena por el trabajo 😄 

![descarga (2)](https://user-images.githubusercontent.com/65229646/97979387-5d8eaf80-1dcf-11eb-9c9a-029ba18c6e46.jpeg)

**Comment by canbot92** [comment]
Muchas gracias Adriiiii :)

Que soy un desastre y leo los correos y se me olvida responder, pero
agradezco un montón tu feedback y me anima muchísimo. Que es verdad que hay
muchas cosas que son nuevas y a veces es fácil frustrarse :D
Un abrazaco!!!
