### ISSUE TITLE
[pandas-project] Ignacio Ordovás Pascual

### ISSUE THREAD

**Issue by ordovas** [ironhack-datalabs/datamad1020#224]
https://github.com/nachordo/pandas-project.git

**Comment by adrianacoca** [comment]
Buenas tardes Nacho! 

Tu proyecto de pandas 🐼 está muy bien! Veo que ya vas cogiendole el tranquillo a la sintaxis de pandas 🚀

Te comento un par de cosas que me han gustado mucho:

- No solo has organizado la limpieza de datos y el análisis en distintos jupyters, sino que usas una estructura de carpetas muy ordenada para almacenar todo👌
-  El README está super claro, se entienden bien los procesos que has seguido y las conclusiones que has sacado🔥
- Has utilizado el markdown de jupyter para explicar los pasos que ibas siguiendo 👍
- Has limpiado los nombres de las columnas mediante distintos metodos como `rename`✅
- Has creado una columna para los meses del año 🙌

Como ya he mencionado antes, has sido super creativo a la hora de utilizar los datos. Has sacado información de donde a simple vista parecían datos super poco útiles. Esto es una cualidad buenísima porque como Data Analysts la mayoría de bases de datos con las que te cruzarás no estarán perfectamente limpias y tendrás que trabajar con ellas igualmente. De hecho tu proyecto me ha recordado a mi proyecto final en algunos aspectos ya que jugué bastante con el natural language processing. Y con eso se pueden hacer cosas muy guays que ya veremos más adelante

Enhorabuena por el trabajo! 🤩 

![descarga (2)](https://user-images.githubusercontent.com/65229646/98023368-1e7c5080-1e07-11eb-9094-bd26756c70a3.jpeg)
