### ISSUE TITLE
[data-cleaning-pandas] Clayton Louden

### ISSUE THREAD

**Issue by WyattGwyon** [ironhack-datalabs/datamad1020#225]
https://github.com/WyattGwyon/data-cleaning-pandas

**Comment by WHYTEWYLL** [comment]
Buenas Clatyon!!!

Antes de nadas felicitarte, por haber arreglado eso problemillas de Github, repos ... 🚀  Vamos con ese proyecto, que tengo alguna que otra cosita que comentarte : 

- Estaría bueno separar entre análisis y cleaning . Nos da muchísimo mas de juego, y organización. Y eso es importante! ya que imagina que alguien quieres el csv limpio para otro departamento o para otros análisis, no le vas a dar todo tu archivos con tus análisis no?

- **Limpieza** : esta muy bien, veo que te has familiarizado con la sintaxis pandas.

- **Análisis** :  me hubiera gustado ver algunos gráficos, que pusieran imagen a tus hipótesis las cuales también podrías haberla redactado a medida o en algún apartado de tu código, junto a tus pensamiento del código.

Tu proyecto de pandas se ha quedado un poco corto en cuanto a trabajo, pero no te preocupes. Es el primero, el de esta semana lo revientas! Somos conscientes de que la información está muy condensada. Las entregas de proyectos deberían ser relativamente limpias, no obstante la próxima vez puedes dejar comentado el código que no has conseguido que funcione o nos lo puedes comentar en el issue para que podamos echarle un vistazo y explicarte maneras en las que lo podrías haber sacado!!

Enhorabuena por el trabajo 😄

![image](https://user-images.githubusercontent.com/49686519/98522523-1a23bd80-2275-11eb-92ee-c2f662dd1d90.png)
