### ISSUE TITLE
[mini-proyect-data-cleaning-pandas] Adrian Madrid

### ISSUE THREAD

**Issue by Adrian96119** [ironhack-datalabs/datamad1020#227]
https://github.com/Adrian96119/data-cleaning-pandas.git

**Comment by WHYTEWYLL** [comment]
Buenos dias, Adrii!!!!! 😄 

FELICIDADES!!! Llegaste a la isla!! En cuanto al proyecto he de decirte que esta bastante bien eh! Hemos llegado y muy bien. De verdad! 

Te comento algunas cosillas para futuros viajes, okey? 

- Estaría bueno separar entre análisis y cleaning . Nos da muchísimo mas de juego, y organización. Y eso es importante! ya que imagina que alguien quieres el csv limpio para otro departamento o para otros análisis, no le vas a dar todo tu archivos con tus análisis no?

- La documentación y comentarios es ESPECTACULAR. 💯 

- **Limpieza**: estoy muy bien.

- **Análisis** Considero que esta muy  claro, además me gusta que hayas jugado con el estilo y el tipo, podríamos haber jugado con algún otro tipo de grafico. Pero esta suuper bien!!

No me enrollo. Sigue así ! 🚀

![images](https://user-images.githubusercontent.com/49686519/97983485-aa758480-1dd5-11eb-9c66-0495c556c977.jpg)
