### ISSUE TITLE
[pandas-project] Isa Searle Riesgo

### ISSUE THREAD

**Issue by isabel-searle** [ironhack-datalabs/datamad1020#228]
https://github.com/isabel-searle/pandas-project.git

**Comment by adrianacoca** [comment]
Buenos días Isa!

Tu proyecto de pandas 🐼 está suuuper bien. Veo que ya vas cogiendole el tranquillo a la sintaxis de pandas 🚀

Te comento un par de cosas que me han gustado y otras que podrías haber tenido en cuenta:
- Has organizado la limpieza de datos y el análisis en distintos jupyters 👌 
- Has dropeado las filas con missing values usando el parámetro de threshold. De esta manera evitamos cargarnos muchas filas que pueden sernos útiles. 🔥 
- Has sacado la columna de meses mediante la columna DATE. Este tipo de enfoque es un ejemplo de que se puede sacar más partido a la información que tenemos mediante métodos para limpiar y manipular datos🙌 
- Cuando limpias las columnas mediante `str.contains`, podrías haberlo hecho mediante un for loop con un diccionario como mencionó Felipe para no tener que copiar y pegar tanto cádigo. Ej: `{"white": "white shark", "tiger": "tiger shark"}`
- En cuanto a el siguiente comentario, has rellenado los missing values  de la tabla SPECIES con Unknown. No obstante, para que los cambios se realicen en el df, debes pasarle el parámetro `inplace=True` de tal manera `df_clean['SPECIES'].fillna("Unknown", inplace=True)`. 
Si haces `df_clean['SPECIES'] = df_clean['SPECIES'].fillna("Unknown")` estás duplicando la columna species, por eso te sale
SPECIES             0
SPECIES          1602
- Has plotteado gráficos usando los datos de varias columnas para llegar a conclusiones entre los países y los años 👍  
- En cuanto al README, procura enfocarlo más como una presentación de tu proyecto. Puedes mencionar cosas que intentaste hacer pero no conseguiste. Pero también puedes utilizar el comentario de la issue para ver estos asuntos conmigo o con Juan. Como por ejemplo mencionar que columnas te han sido más o menos útiles, como has mencionado en el jupyter. Veo que has sacado gráficos y conclusiones bastante interesantes en el jupyter, podrías haberlos puesto en el readme también.

Enhorabuena por el trabajo 😄 

![descarga (2)](https://user-images.githubusercontent.com/65229646/97979387-5d8eaf80-1dcf-11eb-9c9a-029ba18c6e46.jpeg)

**Comment by adrianacoca** [comment]
PD Perdon!!

Se me ha pasado por completo comentarte las funciones que has comentado en el readme.

Puedes aplicar una función a la columna de dates con `.apply` de tal manera:

```
def month_clean(date):
    months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
    for i in months:
        if re.search(i,date):
            return i
        else:
            return "unknown" 
#Duplicas la columna date y le pones month de nombre
df_clean["MONTH"] = df_clean["DATE"] 
#Le aplicas la función a la columna month 
df_clean["MONTH"].apply(month_clean)
```
Es muy parecido al segundo intento que hiciste. No obstante `.apply` itera por las celdas de la columna, por lo tanto el `*` de `def cleaning_months(*x)` no es necesario.
