### ISSUE TITLE
[pandas-proyect] Gonzalo Arroyo

### ISSUE THREAD

**Issue by Gon41** [ironhack-datalabs/datamad1020#229]
https://github.com/Gon41/datamad1020/tree/master/module-1/pandas-project/your-code

**Comment by WHYTEWYLL** [comment]
Buenos dias, Gonzalo!!!!! 😄

FELICIDADES!!! Llegaste a la isla!!

Te comento algunas cosillas para futuros viajes, okey?

- El proyecto debería estar en un repositorio a parte, no dentro de datamada en la master 🙃 

- El Readme muyy bien!

- Estaría bueno separar al menos entre análisis y cleaning . Nos da muchísimo mas de juego, y organización. Y eso es importante! ya que imagina que alguien quieres el csv limpio para otro departamento o para otros análisis, no le vas a dar todo tu archivos con tus análisis no?


- Tener archivos llamados Untitled ⛔ 

- Veo que solucionaste el grafico que trabajamos, dejándolo solo en F y M . 👍 

Me hubiera gustado que hayas jugado con el estilo y con algún otro tipo de grafico. Pero esta bien!! Sigue así ! 🚀

![images](https://user-images.githubusercontent.com/49686519/97985938-3f2db180-1dd9-11eb-9d37-9395db721f98.jpg)
