### ISSUE TITLE
[pandas-project] Borja del Río

### ISSUE THREAD

**Issue by BorjaRio** [ironhack-datalabs/datamad1020#230]
https://github.com/BorjaRio/pandas-project

**Comment by adrianacoca** [comment]
Buenos días Borja, 

Tu proyecto de pandas se ha quedado un poco corto en cuanto a trabajo, la próxima vez deberías trabajar en el proyecto durante el finde y realizar remates el lunes. 

Te comento un par de cosas que me han gustado y otras que podrías mejorar:

- Me gustaría que hubieras organizado la limpieza de datos y el análisis en distintos jupyters
- Has dropeado aquellas filas que contienen valores duplicados en la columna Case Number: `data_clean=df.drop_duplicates(subset="Case Number")` No sólo estás quitando las filas duplicadas sino que también estás quitando las que tienen, por lo tanto te estás cargando las filas que contienen un 0 en case number.
- Has dropeado las filas con missing values con `df.dropna` usando inplace 👌
- Deberías haber manipulado los valores de las celdas para sacarles más partido. Hay mil maneras de hacer esto, entre ellas normalizar las actividades con regex, sacar una columna de months mediante date, etc.

Me da un poco de pena porque sé que poniéndole más interés podrías haber sacado un proyecto mucho más completo...!
