### ISSUE TITLE
[pandas-project] Alba Álvaro

### ISSUE THREAD

**Issue by AlbaAlvaro** [ironhack-datalabs/datamad1020#232]
https://github.com/AlbaAlvaro/pandas-project.git

**Comment by adrianacoca** [comment]
Buenas tardes Alba,

Tu proyecto de pandas 🐼 está suuuper bien. Veo que ya vas cogiéndole el tranquillo a la sintaxis de pandas 🚀

Te comento un par de cosas que me han gustado y otras que podrías mejorar:
 - Tu README, está super detallado  🔥 Has mencionado que columnas te han sido más o menos útiles, cómo las has ultilizado. Veo que has sacado gráficos y conclusiones bastante interesantes en el jupyter, al incluir los gráficos en el readme, se no sale la imagen porque el link no es valido. 😬 
 - Podrías haber organizado la limpieza de datos y el análisis en distintos jupyters.
- Me gusta mucho la técnica que has usado para verificar cuantos valores distintos había entre Case Number 1/Case Number 2 y href/href formula👌
- Has usado el parametro threshold para `.dropna`, por lo tanto sólo has eliminado columnas en las cuales falte un mínimo de valores  🙌
- Has mirado el número de datos validos por columna (super útil para entender la base de datos con la que estamos trabajando) ✅
- Has utilizado `.replace` para limpiar la columna de fatal 👍
- Has plotteado gráficos usando los datos de varias columnas para llegar a conclusiones 
- A pesar de que no las hayas usado para tus hipótesis, habría estado bien que hubieses 'jugado' un poco con las columnas `["Date", "Year", "Country", "Activity", "Fatal (Y/N)"]` ya que aunque no estén del todo completas, se les podía sacar más partido. (Ej: Sacar los meses en los que ocurren los ataques mediante la columna Date)

El proyecto está muy bien en general, enhorabuena por el trabajo 😄

![descarga (2)](https://user-images.githubusercontent.com/65229646/97988143-cdeffd80-1ddc-11eb-87b6-6197429cc86f.jpeg)
