### ISSUE TITLE
[pandas-project] Alberto Jiménez

### ISSUE THREAD

**Issue by Albertojd** [ironhack-datalabs/datamad1020#233]
https://github.com/Albertojd/data-cleaning-pandas

**Comment by adrianacoca** [comment]
Buenas tardes Alberto!

Tu proyecto de pandas 🐼 está muy bien! Veo que ya vas cogiendole el tranquillo a la sintaxis de pandas 🚀

Te comento un par de cosas que me han gustado y otras que podrías mejorar:

- En cuanto al README, se entiende bastante bien los procesos que has seguido. También me gusta ver que has presentado tus hipótesis aquí 🔥 
- Has organizado la limpieza de datos y la representación en distintos jupyters 👌
- Has limpiado los nombres de las columnas mediante el strip y replace ✅
- Has usado replace para rellenar los missing values de cada columna 🙌 Como mencionó Felipe, habría sido muy útil hacerlo mediante un diccionario. 
- Has rellenado los missing values de las columnas numéricas usando otro método ✔️ 
- Como mencionamos, habría estado muy bien que los gráficos de los años estuviesen en orden. Esto lo podrías haver usando `.sort_index()`, ya que el año es el indice de `df_graph["Year"].value_counts()`
- Me gustaría haber visto algún método más de limpieza de datos. Uno que es bastate común es df.dropna(inplace = True) para cargarte aquellas filas con missing values. Hay una manera de dropear las filas sólo si tienen un mínimo de missing values mediante el threshold. Ej: df.dropna(inplace = True, thresh=5) --> eliminar la fila sólo si hay 5 o más missing values. De esta manera evitamos cargarnos aquellas filas que no están muy completas.


Enhorabuena por el trabajo 😄

![descarga (2)](https://user-images.githubusercontent.com/65229646/98009117-7dd16500-1df5-11eb-99db-d641c7e1321d.jpeg)
