### ISSUE TITLE
[pandas-project] Angela Gomez

### ISSUE THREAD

**Issue by angelagomezf** [ironhack-datalabs/datamad1020#234]
https://github.com/angelagomezf/pandas-project

**Comment by WHYTEWYLL** [comment]
Buenos dias, AG!!!!! 😄

FELICIDADES!!! Llegaste a la isla!! En cuanto al proyecto he de decirte que esta bastante bien eh! Hemos llegado y muy bien. De verdad!

Te comento algunas cosillas para futuros viajes, okey?

- Estaría bueno separar entre análisis y cleaning . Nos da muchísimo mas de juego, y organización. Y eso es importante! ya que imagina que alguien quieres el csv limpio para otro departamento o para otros análisis, no le vas a dar todo tu archivos con tus análisis no?

- La documentación y comentarios es MUY BIEN. 💯. Así puedo saber que estabas pensando! 👍 

- Limpieza: que tanto nos preocupaba, esta muy bien. Has sido capitana y has tomado tus decisiones. Si que es cierto que por ejemplo en ciertas columna como en sexo ,podríamos haber reducido y organizado un poco mas, para no tener  F M O M LLI N, no?  Como han hecho algunos compañeros, esta mañana.

- Análisis -> Considero que esta muy claro, además me gusta que hayas jugado con el estilo y el tipo, podríamos haber jugado con algún otro tipo de grafico. Pero esta suuper bien!!

No me enrollo. Sigue así ! 🚀

![images](https://user-images.githubusercontent.com/49686519/97993149-f4656700-1de3-11eb-9f9b-0c5e9ee64a5f.jpg)
