### ISSUE TITLE
[pandas-project] Alejandro Medina

### ISSUE THREAD

**Issue by medinaale91** [ironhack-datalabs/datamad1020#235]
https://github.com/medinaale91/Miniproject_2

**Comment by adrianacoca** [comment]
Buenas tardes Ale,

Tu proyecto de pandas 🐼 está muy bien! Veo que ya vas cogiendole el tranquillo a la sintaxis de pandas 🚀

Te comento un par de cosas que me han gustado y otras que podrías mejorar:
-  ⚠️ ⚠️  README ⚠️ ⚠️   es super importante que expliques aqui tu proyecto ya que es el 'documento' en el que presentas el proyecto. Aqui puedes mencionar aspectos como: de qué se trata el proyecto - qué estás intentando hacer, qué procedimientos has usado para esto y porqué, también puedes exponer los gráficos y conclusiones que has sacado mediento los datos. 
- Has organizado la limpieza de datos y el análisis en distintos jupyters 👌
- Has limpiado los nombres de las columnas mediante rename ✅
- Has dropeado las filas con missing values con df.dropna utilizando el threshold para intentar mantener más datos 👍
- Has normalizado los datos mediante varias técnicas adáptandote a la más conveniente para cada circunstancia 🙌
- ⚠️ ⚠️  Para usar el csv limpio debes exportarlo --->`df.to_csv(<path where you want to store the exported CSV file\File Name.csv>)` y luego importarlo en lugar de volver a ejecutar todo el archivo de python `clean.ipynb`
- En cuanto a tu comentario ---> una vez limpiados todos los datos, pretendía mostrar una gráfica que sacara en qué paises practicar surf era más peligroso, pero no he sabido como plantearlo para mostrar esa gráfica. 
Podrías haber agrupado por país con un `groupby` y mostrado un gráfico de la columna "Fatal". El uso del groupby puede dar muchisimo juego a la hora de analizar y representar los datos. Te paso la documentación  de groupby
 ----> [https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html](url)

En cuanto a tu comentario del final, no te agobies! Somos conscientes de que la información está muy condensada. Las entregas de proyectos deberían ser relativamente limpias, no obstante la próxima vez puedes dejar comentado el código que no has conseguido que funcione o nos lo puedes comentar en el issue para que podamos echarle un vistazo y explicarte maneras en las que lo podrías haber sacado!! 

Enhorabuena por el trabajo 😄

![descarga (2)](https://user-images.githubusercontent.com/65229646/98005813-c4bd5b80-1df1-11eb-8abd-2bd188a90574.jpeg)
