### ISSUE TITLE
[pandas-project] Blanca de Ochoa

### ISSUE THREAD

**Issue by BlancadeOchoa** [ironhack-datalabs/datamad1020#236]
Hola Juan!
Se me ha hecho tarde y no me ha dado tiempo a hacer el read me, y quiero escribirlo bien.
Losiento...Mañana lo hago sin falta

https://github.com/BlancadeOchoa/data-cleaning-pandas.git

**Comment by WHYTEWYLL** [comment]
Buenos dias, Blanca!!!!! 😄

FELICIDADES!!! Llegaste a la isla!! En cuanto al proyecto he de decirte que esta bastante bien eh! Hemos llegado y muy bien. De verdad!

Te comento algunas cosillas para futuros viajes, okey?

- Bien ahí usando chardet!! 😉 

- Estaría bueno separar entre análisis y cleaning . Nos da muchísimo mas de juego, y organización. Y eso es importante! ya que imagina que alguien quieres el csv limpio para otro departamento o para otros análisis, no le vas a dar todo tu archivos con tus análisis no?

- La documentación y comentarios es ESPECTACULAR. 💯

- Limpieza: esta bastante bien, me gusta esas lambda. Y que hayas salido de la encrucijada, con tus decisiones! Si que es verdad, que podríamos buscarnos la mañanas a lo mejor con laguna funciones, para no agrupar tanto en unknown cuando si que sabemos a que pertenecen no? Como en la columna de sexo. 

- Análisis --> Me gusta que hayas jugado con el estilo y con el  tipo de grafico. Esta súper bien!!

No me enrollo. Espero que hayas cogido alguna idea de los compis. En cuanto al Readme, hazlo cuanto tengas un hueco , pero que no te quite mucho tiempo, ya cuando todo pase tendrás tiempo de ponerlo mas bonito. Pero esta bien. Sigue así ! 🚀

![images](https://user-images.githubusercontent.com/49686519/97998580-95572080-1dea-11eb-9067-a05e4bcda283.jpg)
