### ISSUE TITLE
[pandas-project] Edu Oporto

### ISSUE THREAD

**Issue by EduOporto** [ironhack-datalabs/datamad1020#237]
https://github.com/EduOporto/ironhack-projects/tree/main/pandas-project

Te dejo lo mío por aquí. Me falta el README, confieso. Se me ha complicado un poco los plots esta tarde, pero mañana estará hecho y bien hecho. A parte debería mejorar un poco las explicaciones de como he limpiado el dataframe, profundizaré en ello.

Por cierto, el trabajo está en inglés, que como dijisteis que esto va a servir de portfolio pues pensé que mejor así, además me sirve para que no se me oxide!

**Comment by WHYTEWYLL** [comment]
Hola Eduuu!!!!! 😄

FELICIDADES!!! Llegaste a la isla!! En cuanto al proyecto he de decirte que esta bastante bien eh! Hemos llegado y muy bien. De verdad! Si lo dices todo, que voy a decir yo entonces?? AJAJJAJA joking 

Te comento algunas cosillas para futuros viajes, okey?

- Bien separando entre análisis y cleaning . Nos da muchísimo mas de juego, y organización. Y eso es importante! Ya que imagina que alguien quieres el csv limpio para otro departamento o para otros análisis, no le vas a dar todo tu archivos con tus análisis no?

- La documentación y comentarios ... Hay que darle una vuelta, no te digo nada porque ya lo sabes.

- Limpieza: muy buen trabajo, que te voy a decir? Pero lo mismo que se ha comentado esta mañana , tienes mucho código repetido que podríamos refactorizarlo para que en vez de escribir las mismas líneas de código con alguna modificación , utilizar un diccionario , lista...

- Cuidado con los NaN values, que la exportas con ellos a la visualización. Que además de la forma que lo importas en la visualización, tienes una columna que copia el índice, eso no puede pasar.

- Análisis Considero que esta muy claro, además me gusta que hayas jugado con el estilo y el tipo. Pero tienen un currazo todos los gráficos , están suuper bien!!

No me enrollo. Btw, estaría bien que metieras en una carptea los csv, y no todo junto al mismo nivel con los jupyters. Sigue así ! 🚀

![images](https://user-images.githubusercontent.com/49686519/98005305-2df09f00-1df1-11eb-9ffd-e46c62ed8ca1.jpg)
