### ISSUE TITLE
[pandas-project] Gerardo Vitale

### ISSUE THREAD

**Issue by gerardovitale** [ironhack-datalabs/datamad1020#238]
https://github.com/gerardovitale/data-cleaning-pandas

**Comment by adrianacoca** [comment]
Buenas tardes Gerardo! 

Tu proyecto de pandas 🐼 está muy bien! Veo que ya vas cogiendole el tranquillo a la sintaxis de pandas 🚀

Te comento un par de cosas que me han gustado y otras que podrías mejorar:

- Has organizado la limpieza de datos y el análisis en distintos jupyters 👌
-  El README está bastante claro, se entiende bien los procesos que has seguido🔥 Podrías haber incluido algunos gráficos con tus conclusiones.
- Has mirado el nombre de datos validos por columna (super útil para entender la base de datos con la que estamos trabajando) ✅
- Has dropeado las filas con missing values con `df.dropna()`. Hay una manera de dropear las filas sólo si tienen un mínimo de missing values mediante el threshold. Ej: `df.dropna(inplace = True, thresh=5)` --> eliminar la fila sólo si hay 5 o más missing values. De esta manera evitamos cargarnos muchas filas que pueden sernos útiles.
- Has plotteado gráficos ordenando el x-axis 👍
- Podrías haber sacado algunos barplots muyy chulos usando el groupby (combinando datos de dos columnas)
Te dejo la documentación por si le quieres echar un vistazo! [https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html](url)
 🙌

Enhorabuena por el trabajo! 🤙

![descarga (2)](https://user-images.githubusercontent.com/65229646/98023368-1e7c5080-1e07-11eb-9094-bd26756c70a3.jpeg)
