### ISSUE TITLE
[pipelines-project] Cristina Arenas Izquierdo

### ISSUE THREAD

**Issue by crisarenas** [ironhack-datalabs/datamad1020#293]
https://github.com/crisarenas/W3-pipeline-project

**Comment by adrianacoca** [comment]
Buenos días Cris!! 

Te comento un par de cosillas sobre el proyecto: 

**README:** Explica los datos iniciales y el análisis final bastante bien. Habría estado bien una sección que abarcase el enfoque del proyecto de enriquecer el datatset. Pero en general bastante bien! ✅ 

**Limpieza de datos:** Has investigado el contenido del dataset y has visto que era una dataset bastante limpio. Por lo tanto tampoco has tenido que usar demasiadas técnicas para limpiarlo, esto está bien hecho ya que cuando los datos están bastante limpios hay que mantener la máxima info posible.  🙌 

**Enriquecimiento del dataset:**
Como ya comentamos, has tenido problemas enriqueciendo tu dataset.
Le he echado un vistazo a la tabla temperaturas de wikipedia. Estabas suuper cerca de conseguirlo, solo te hacía falta sacar el `.text` para cada item de rows, que pena!! Te envío la solución que he sacado yo partiendo de tu codigo:
```
#Una vez que has conseguido sacar rows, creamos una lista vacía y vamos iterando por rows para sacar el .text para cada país
temperatures = []
for i in range(len(rows)):
    temperatures.append(rows[i].text)
#Nos queda una lista de strings con la info del país y la temperatura ['\n\xa0Burkina Faso\n28.29\n', '\n\xa0Mali\n28.25\n', '\n\xa0Kiribati\n28.20\n',...] 
#Usamos regex para limpiar el principio del string
temperatures = [t.replace("\n\xa0", "") for t in temperatures]
#Usamos split para separar el nombre de la temperatura en una lista
temperatures = [t.split("\n") for t in temperatures]
#Output: [['Burkina Faso', '28.29', ''], ['Mali', '28.25', ''], etc]
```
Con esta lista ya serías capaz de incluir las temperaturas medias de cada país en tu dataset 😄 

Creo que el concepto de web scrapping lo has entendido, pero necesitas algo más de práctica con las estructuras de las urls, lo cual harás más adelante en el bootcamp. No obstante sé que le has puesto mucho esfuerzo a tu trabajo, sigue así!! 🚀 🚀 🚀
