### ISSUE TITLE
[pipelines-project] Ignacio Ordovás Pascual

### ISSUE THREAD

**Issue by ordovas** [ironhack-datalabs/datamad1020#307]
https://github.com/nachordo/pipelines-project.git

Pues ahí va mi projectillo: sobre los 500 mejores álbumes 
(según la revista Rolling Stones, las culpas a ellos si no estás deacuerdo con la lista :grin:   )

**Comment by WHYTEWYLL** [comment]
Hola Nacho!!! 😄 

WOW esta super guay!! 100% que no vamos a coincidir porque mis gustos son un tanto asimetricos aahahhaha dificilmente que este deacuerdo. 

-En cuanto al curro esta muy guay, has cumplido con todos los objetivos que estaban marcados. Ademas veo que has hecho un esfuerzo por la organizacion, lo cual es top! He visto que has sido onbservador y medio que te has insipirado en la disposicion de los labs, para tu repositiorio. Lo unico que your-code no tiene sentido si te fijas. La organizacion adecuada seria los jupyter fuera , que son como lo main. Y en vez de, que la carpeta se llamase 'your-.code' se llamase 'src' de source , y ahi dejar los py que son las dependecias de tu main. De acuerdo? 

-Muy bien con esos .py , y esas funciones sacandolas de los jupyter 👍 

- El Readme esta super bien! Ya me daras algun tip para hacerlos jeje

- Cuidado con los try except, que no se conviertan en una constante en tu código

Esta SUPER BIEN! No tengo mas que decirte , sigue así!! 🚀 🚀 🚀 

![niveles-de-clases-sociales-clase-alta-spotify-premium-ase-media-48933124](https://user-images.githubusercontent.com/49686519/98671939-4ca4e780-2355-11eb-8d9d-0477246c7806.png)
