### ISSUE TITLE
[pipelines-project] Isa Searle Riesgo

### ISSUE THREAD

**Issue by isabel-searle** [ironhack-datalabs/datamad1020#308]
Selenium me ha traído por el camino de la amargura...

https://github.com/isabel-searle/pipelines-project.git

**Comment by WHYTEWYLL** [comment]
Hola Isa!!! 🤠 

Vamos con ese proyecto!!! Fuiste valiente cogiendo Selenium, lo que te dije. Enhorabuena! No te preocupes vas a revisarlo y te comento cositas.

- Readme -> Estaria bien,  seguir algun tipo de estructura . Utilizando MD, como por ejemplo explicas la intención de tu proyecto, cómo tienes pensado hacerlo, los pasos que has ido siguiendo...

- Importante separar análisis y limpieza, y archivos recurso como los de webscrapping , en una carpeta.  Es importante, que si yo me meto a tu repositiorio. Donde tengo que hacer click para iniciar, o ver lo que quiera ver.

- Es importante la documentación tanto por tu código, como en que hace cada funcion que haces. 

- A pesar de que no hayas conseguido lo que querías, has cumplido con todos lo objetivos del proyecto. Enhorabuena.

- Te paso por slack, una solucion simple para poder scrapear esa pagina. 

Buen trabajo. Sigue asi!!! 🚀 🚀 🚀 🚀
