### ISSUE TITLE
[pipelines-proyect] Borja del Rio

### ISSUE THREAD

**Issue by BorjaRio** [ironhack-datalabs/datamad1020#309]
https://github.com/BorjaRio/pipelines-project

**Comment by WHYTEWYLL** [comment]
Borjitaa!!!  🤠 

Titan, como estamos? Poquito que decirte, esta todo dicho. Lo bueno y lo malo. Lo importante es la actitud y la mentalidad que tienes activada. Es la actitud ganadora. Sigue asi!! 🚀 

![5daaed248effe](https://user-images.githubusercontent.com/49686519/98667234-70186400-234e-11eb-9ca5-456e5ba7ec11.jpg)
