### ISSUE TITLE
[pipelines-project] Clayton Louden

### ISSUE THREAD

**Issue by WyattGwyon** [ironhack-datalabs/datamad1020#311]
https://github.com/WyattGwyon/data-pipeline

**Comment by adrianacoca** [comment]
Buenas tardes Clayton!

Sé que has puesto trabajo en el proyecto 🚀 pero se te ha complicado todo a la hora de poder enriquecer la base de datos porque no había muchas APIs gratis para el tema que habías escogido. Te paso un par de comentarios: 

**README:** Está bastante bien y se entiende tu approach hacia el proyecto! Una sugerencia para el futuro sería organizar mas la información para que sea más 'fácil' de leer. Es decir, usando subtítulos, algún extracto de código que ayude a explicar tu proyecto, imágenes, etc. 

**Data Cleaning:** Veo que has limpiado los datos, Ya que tenías esto hecho, podrías haber exportado el csv limpio para usarlo en el jupyter en el que enriqueces los datos en lugar de usar el dataset sucio. Se me ocurre manera de sacarle más partido a este dataset con lo que ya tenías: creando una columna nueva que sacase las estaciones (invierno, primavera, verano, otoño). Esto te habría dado una idea general de qué productos se consumen más cuando hace calor o frio.

**Enriquecimiento de datos:** Me gusta mucho la idea de los non valid words para sacar las categorías bien, pero teniendo en cuenta la cantidad de elementos que estás buscando, probablemente haya más palabras que no encajen con tu dataset inicial. Una manera de hacer este ejercicio para encontrar los precios para cada producto habría sido mediante el match de regex de tal manera:
 - loop por el set de elementos de el dataset inicial
 -  usar un match para todos los elementos de Waitrose que contengan este nombre 
 - coger el precio para este elemento mediante la lista que has sacado en el jupyter

Creo que tu proyecto tenía mucho potencial!! 🙌 🙌 Te ha faltado un poco de tiempo, para el próximo proyecto procura tenerlo bastante acabado para el lunes por la mañana así solo te quedarán los últimos remates y las dudas que podrás solucionar conmigo o Juan!
