### ISSUE TITLE
[pipelines-project] Alba Álvaro

### ISSUE THREAD

**Issue by AlbaAlvaro** [ironhack-datalabs/datamad1020#312]
https://github.com/AlbaAlvaro/pipelines-project.git

Ha sido todo un poco desastre, lo podía haber hecho mejor la verdad pero se me echó el tiempo encima :(

**Comment by WHYTEWYLL** [comment]
Hola Alba!!! 😄 

Que taaaall ? Hija mia, si esto es un desastre para ti y con poco tiempo. No me quiero imaginar en el futuro! Ya hemos pasado un finde mas, una aventura más superada. Esta todo dicho, INCREIBLE TRABAJO. Sigue así, vas increíble!!! 🚀 

![120578923_782564965916804_3565278452490624200_n](https://user-images.githubusercontent.com/49686519/98668700-8cb59b80-2350-11eb-9caa-f704a956a1ef.jpg)
