### ISSUE TITLE
[mini-proyect-pipelines] Adrian Madrid

### ISSUE THREAD

**Issue by Adrian96119** [ironhack-datalabs/datamad1020#313]
https://github.com/Adrian96119/Mini-proyect-pipelines.git

**Comment by adrianacoca** [comment]
Buenas tardes Adri!!

En general tu proyecto está bastante bien, has conseguido enriquecer tu base de datos mediante APIs y web scraping que es de lo que se trataba el proyecto! ✅ 

**README:** El contenido en sí está bien!! pero si ves el readme desde Github verás como la estructura es un poco liosa y lo hace difícil de leer, de repente hay Mayusculas, flechas, letra en negrita, pero la estructura no se entiende muy bien. Échale un vistazo a la sintaxis de markdown! También podrías haber explicado un poco la distribución de los ficheros porque es un poco complicado entenderla. 

**Limpieza de datos:**  Cuando escoges los directores que quieres, en lugar de copiar y pegar el código podrías haberlo hecho con `loc` pasándole una lista de los directores que te interesan.
```
directores = df[(df["Director"] == "Ford John")     
                | (df["Director"] == "Fellini Federico") | (df["Director"] == "Almodóvar Pedro")
                | (df["Director"] == "De Palma Brian")   | (df["Director"] == "Coppola Francis Ford")
                | (df["Director"] == "Leone Sergio")     | (df["Director"] == "Spielberg Steven")
                | (df["Director"] == "Eastwood Clint")   | (df["Director"] == "Cameron James") 
                | (df["Director"] == "Kubrick Stanley")  | (df["Director"] == "Scorsese Martin")]
```
-----> `df.loc[df['Direrctor'].isin(list_of_directors)]`

**Enriquecimiento de datos:** Cuando enriqueces los datos, no hace falta que hagas cada llamada a una api en un archivo distinto. Te hubiese facilitado un poco la vida tenerlo en el mismo jupyter e ir metiendo la info en las bases de datos en lugar de tener que copiar y pegarla de un archivo a otro.  Veo que has usado tanto web scraping y APIs!! 🚀  Y has conseguido sacar bastante info 🙌 🙌 

**Análisis de datos:** Has sacado gráficos bastante interesantes mediante los ratings que has incorporado a la base de datos! Habría estado guay que hubieras incluido algunos en el README en un apartado de Conclusiones.
