### ISSUE TITLE
[pipelines-project] Angela Gomez

### ISSUE THREAD

**Issue by angelagomezf** [ironhack-datalabs/datamad1020#314]
https://github.com/angelagomezf/pipelines-project

**Comment by adrianacoca** [comment]
Buenas tardes Angela!!

Tu proyecto está bastante bien, has conseguido pelearte con la API de Spotify, que no es tan facil como parece 😅 y la estructura de los archivos es bastante clara! 🙌 

**README:** Está bien estructurado pero te ha faltado expandirte un poco más! Podrías haber explicado cómo has usado la API, que información has conseguido sacar, qué conclusiones has sacado y sus gráficos respectivos.

**Limpieza de datos:** La limpieza inicial de datos está muy bien y has justificado porqué querías trabajar con los musicos mediante un gráfico ✅  

**Enriquecimiento de datos:** Has conseguido sacar los followers de Spotify para cada artista y las fotos 🕺 sin necesitar los artist IDs. Parece que era un poco más simple de lo que pensábamos 😅 Creo que podrías haber intentado sacar algo más de info mediante la API si hubieras tenido más tiempo.

**Análisis de datos:** La visualización de datos esta bastante bien! Habría estado bien que hubieses intentado sacar más gráficos con la info que tenías comparando los followers en Spotify con otras métricas de instagram. 

Por lo general el proyecto está bien, has conseguido enriquecer la base de datos mediante una API, que es de lo que se trataba el proyecto. No obstante, creo que con un poco más de tiempo podrías haberle sacad muchiisimo partido a la API. La próxima vez intenta tener el proyecto más machacado antes del Lunes para que no te falte tiempo!! 🙏
