### ISSUE TITLE
[pipelines-project] Alejandro Medina

### ISSUE THREAD

**Issue by medinaale91** [ironhack-datalabs/datamad1020#315]
https://github.com/medinaale91/miniproject_3

**Comment by WHYTEWYLL** [comment]
Hola Ale!!! 🤠 

Que tal todo???? Buah tu trabajo esta increíble tio! Felicitaciones!!! Tengo poquito que comentarte, ya esta todo dicho. Lo único eso si, la organización IMPORTANTE.  Podemos crear una carpeta para guardare los csv, fotos... es decir recursos y que nos quedase únicamente a primer nivel, los mains. Pero vamos, que esta INCREIBLE. Sigue así!! 🚀 

![download](https://user-images.githubusercontent.com/49686519/98670357-e28b4300-2352-11eb-8f50-64c3cc922eb9.jpg)
