### ISSUE TITLE
[pipelines-project] Blanca de Ochoa

### ISSUE THREAD

**Issue by BlancadeOchoa** [ironhack-datalabs/datamad1020#316]
Hola Adri!

Despues de pelearnos muchisimo con la api porfiin hemos conseguido utilizarla y coger info de ella.

La estructura del proyecto de los archivos que he subido sería ;
- cleaning_data: es donde limpio el data set inicial previo a introducirle datos con la api
- spotify_api: es donde utilizo la api de spotify para enriquecer el dataframe
- data_representation: es donde realizo las graficas y escribo las hipotesis/conclusiones.
(de todas maneras viene explicado en el readme)

Muchisimas gracias!

https://github.com/BlancadeOchoa/W3-Pipelines_project.git

**Comment by adrianacoca** [comment]
Buenas tardes Blanca!!

Congrats, has conseguido pelearte con la API de Spotify, que no es tan facil como parece 😅 y tus archivos están bastante bien organizados! 🙌 (tip: la próxima vez podrías usar carpetas para separar los jupyters de los csv)

**README:** Está bastante bien! Podrías haber incluido gráficos e información sobre conclusiones has sacado. Pero por lo general 👍 

**Limpieza de datos:** Has analizado la base de datos para asegurarte de que no estaba demasiado sucia y has normalizado los datos ✅

**Enriquecimiento de datos:** Has conseguido sacar los followers de Spotify para cada artista y las fotos 🕺 sin necesitar los artist IDs. Parece que era un poco más simple de lo que pensábamos 😅 Creo que podrías haber intentado sacar algo más de info mediante la API si hubieras tenido más tiempo.

**Análisis de datos:** La visualización de datos esta bastante bien! Me gusta ver que estás investigando las correlaciones entre columnas, pero creo que por los scatter graphs que han salido, no parece que haya tanta correlación (esto es algo que continuaremos viendo con detalle el resto de la semana). Habría sido interesante ver la correlación entre los followers y el chart position (que probablemente estén bastante correlacionados). 

Por lo general el proyecto está bien, has conseguido enriquecer la base de datos mediante una API, que es de lo que se trataba el proyecto! 🚀
