### ISSUE TITLE
[pipeline-project] Alberto Jiménez

### ISSUE THREAD

**Issue by Albertojd** [ironhack-datalabs/datamad1020#317]
https://github.com/Albertojd/pipelines-project

**Comment by Albertojd** [comment]
No he conseguido sacar ninguna conclusión clara con los datos que tenía, simplemente sacar algún gráfico sin relevancia.
He dedicado muchas horas, he dado demasiadas vueltas, he cambiado muchas veces da dataset, y no estoy contento con el resultado; era un proyecto que me apetecía mucho pero no he sido capaz de aprovecharlo, espero en un futuro volver a él y hacer algo totalmente distinto.

**Comment by WHYTEWYLL** [comment]
Hola Alberto!!! 🤠 

Que tal estamos!!!?? NO digas esas cosas. Lo importante es lo que le he has dedicado muchas horas, muchas vueltas e intentos. Eso es lo importante, de verdad eso es lo mas importante.  Y se nota por tu código. Es mas importante afianzar los conocimientos, contenido y trabajar con las herramientas. Que dejar una cosita bonita. Ya tendrás tiempo, de hacer algo mas bonito o más estético. Muchas veces el hecho de que no tenga conclusión ES una conclusión. Y no esperes volver, porque cuando acabes con todo lo que sabes **DEBES** volver, y retocarlo!

En cuanto al proyecto, cumples todos lo objetivos marcados para este proyecto en cuanto a enriquecimiento , tratamiento de api... Así que genial! Lo único malo a remarcar que **NO** puede volver a pasar, es la organización, no puedes tener 2 archivos main, 3 carpetas de recursos , archivos sueltos al nivel del readme... E la carpeta de checkpoints de jupyter debe ir al gitignore para no subirlo.

Sigue así! No te desanime, el siguiente proyecto te saldra como quieras, estas asentado  las bases!! 🚀 🚀 🚀
