### ISSUE TITLE
[pipelines-project] Edu Oporto

### ISSUE THREAD

**Issue by EduOporto** [ironhack-datalabs/datamad1020#318]
https://github.com/EduOporto/ironhack-projects/tree/main/pipelines-project

**Comment by adrianacoca** [comment]
Buenas tardes Edu!!

**README:**  El readme esta bastaante bien 👍 Podrías haber incluido algunos gráficos con conclusiones.

**Data Cleaning:** Por lo general la limpieza está bastante bien. Has unido las bases de datos ✅ , pero podrías haber dropeado la columna `Unnamed: 0` mediante una función que cogiese cada df como parámetro mediante un loop . 

**Enriqueciendo datos:** Has hecho web scraping y has conseguido sacar un montón de datos 🙌  Tu código tiende a repetirse mucho, por ejemplo cuando estás haciendo scraping para cada DataFrame:

```
shooting_df = shooting_df.append(pd.Series(scraper.fplayer_scrap(row['sofifa_id'], data, 'shooting_df'), 
index=shooting_df.columns), ignore_index=True)
```

Podrías haberlo hecho mediante una función a la que le pasas el nombre de cada df mediante un for loop en lugar de escribir este código para cada Data Frame. 

**Analizando datos:** Creo que con la cantidad de datos que tenías podrías haber sacado más gráficos. No obstante el principal objetivo del proyecto era enriquecer una base de datos y lo has hecho bastante bien!
