### ISSUE TITLE
[pipelines-project] Candela García

### ISSUE THREAD

**Issue by canbot92** [ironhack-datalabs/datamad1020#319]
https://github.com/candelagarciafdez/project-film-database

**Comment by WHYTEWYLL** [comment]
Hola Candelaaa!! 🤠 

Como andamos? Poquito te voy a decir, porque la corrección ya la hicimos en clase. Bien presentado! Simplemente remarcar algunos puntos:

- Carpetas y organización, no solo para ti. Sino para el resto, que entre a tu repositorio...

- Los csv, en una carpeta a parte de los jupyters, py ...

En cuanto al resto, codigo y trabajo en general ya se ha comentado todo. Felicitarte que esta muy guay!! Siempre es complicado encontrar peliculas buenas! Sigue asi!! 🚀 

![download](https://user-images.githubusercontent.com/49686519/98667009-20d23380-234e-11eb-95a1-a6a47d50548c.jpg)
