### ISSUE TITLE
[pipelines-project] Carlos Vila-San Juan

### ISSUE THREAD

**Issue by carlosvilasanjuan** [ironhack-datalabs/datamad1020#320]
https://github.com/carlosvilasanjuan/data_pipe.git

**Comment by adrianacoca** [comment]
Buenos días Carlos!

Por lo general el proyecto está muy bien!! Los archivos están bastante bien organizados. (Tip: en un futuro podrías separar los csv de los jupyter en carpetas)

**README:** Está muy organizado y has incluido tus conclusiones, problemas, etc. También podrías haber incluido los pasos que seguiste para enriquecer el DataFrame o incluso algunos gráficos para complementar las conclusiones. 

**Limpieza de datos:** Has elegido el dataset bastante bien, estaba bastante limpio. 😄  Cuando haces `removing end space` y `removing comas`, tu código se repite mucho y lo único que cambia es el nombre de la columna. Podrías haber hecho esto con un loop para no tener que copiar y pegar el código. De la siguiente manera:
```
columns = ['XAUUSD Open', 'XAUUSD Low', 'XAUUSD High', 'XAUUSD Close', 'XAUUSD Adj. Close']
for column in columns:
    gold[column] =[re.sub(' ', '', ele) for ele in gold[column]]
    gold[column] = [re.sub(',','', ele) for ele in gold[column]]
```

**Enriquecimiento de datos:** Has usado la api de Fed para sacar más datos!! 🚀 🚀 No estoy segura del tema de los tokens para esta API, pero veo que has subido el API key. Procura acostumbrarte a no incluir esto en los jupyter, sino hacerlo con el `.env` como aprendisteis en el lab. 

**Análisis de datos:** Has sacado unos cuantos gráficos chulos! Que pena que no estén en el readme. 😅 

Buen trabajo!
Sigue así 💪
