### ISSUE TITLE
[pipeline-project] Gerardo Vitale

### ISSUE THREAD

**Issue by gerardovitale** [ironhack-datalabs/datamad1020#321]
https://github.com/gerardovitale/global-power-plants-pipeline

**Comment by WHYTEWYLL** [comment]
Hola Gerar!!! 🤠

Que tal tío? Como estamos. Hoy con Tableau LETS GOOO!! 💪  En cuanto al proyecto , FELICIDADES TIO! Una semana mas, el viaje se ha completado. Congratulations !!! Tengo unas cositas que comentarte , la organización lo que ya hemos comentado. No tengo mas que decirte. Para futuras veces es nuestro 💪 . Muchas veces es mejor hacer menos y bien que mucho. Pero en este caso se nota que has peleado, y eso me gusta. Ya tendremos tiempo, de modificar y ponerlo espectacular. Sigue así!! 🚀 🚀 🚀 

![unnamed](https://user-images.githubusercontent.com/49686519/98689864-a1079180-236c-11eb-8744-0d3bb762c8e8.jpg)
