### ISSUE TITLE
[pipelines-project] Gonzalo Arroyo

### ISSUE THREAD

**Issue by Gon41** [ironhack-datalabs/datamad1020#322]
https://github.com/Gon41/Proyecto-Pipelines

Buenas,

Está bastante desorganizado y bastante simple. Mi idea era concentrarme en el data scraping, e intentar hacerlo simple, para por lo menos terminar el proyecto, y poco a poco ir enriqueciéndolo añadiendo pequeñas ideas.

He conseguido sacar el web scraping después de muchos tutoriales (cosa que no sabes de lo que me enorgullezco), pero se me ha hecho mucha bola muchas cosas de los dataframe y de los gráficos que no entendí y asimilé en su momento que he ido arrastrando. He invertido mucho tiempo en intentar solucionar pequeñas cosas y me ha faltado mucho mucho tiempo.

El tema del inglés es un palo en la rueda que me está matando, pero bueno poco a poco con el traductor voy haciéndome, pero tardo horrores. Necesito agilizar mis tiempos. 

Me he visto más suelto buscando las cosas en internet y leyendo la documentación (cosa que se me antojaba imposible antes).

Y la verdad, que  me ha gustado el proyecto y quería volver a utilizar el web scraping con otras filas que no aparecían en esa página web, pero no me ha dado tiempo, ya no te digo para meter las funciones o los list comprenhensions...

Voy extremadamente lento en el bootcamp pero bueno paso a paso, no hay otra y no soy capaz de ir más rápido. Por lo menos ahora voy gestionando mejor la ansiedad, que la primera y segunda semana me mató física y mentalmente.

No se si me podéis dar algún consejo que me pueda ayudar con todo el general.

Gracias!!

**Comment by adrianacoca** [comment]
Hola Gon!!

Me alegra muucho ver que te estás peleando con internet para sacar adelante los proyectos!! Y eso es una herramienta suuuper importante 💪 Asi que enhorabuena por eso 😄 

En cuanto a el proyecto te comento un par de cosas:

**README:** Te doy un consejo, es mucho mejor ir haciendo el readme mientras vas haciendo el proyecto incluyendo cosas como:
 - explicas la intención de tu prpyecto
 - cómo tienes pensado hacerlo
 - los pasos que has ido siguiendo
 - los problemas que has tenido
 - las conclusiones que has sacado
 - posibles mejoras
Porque si vas un poco apretado de tiempo en el proyecto ya lo tendrás medio hecho si lo has ido retocando sobre la marcha

**Limpieza de datos:** Tu DataFrame inicial estaba bastante limpio, asi que bien escogido! No hacía falta realizar la limpieza en dos jupyters distintos. Pero igual habría sido más ordenado separarlo en `data cleaning` (limpieza del database) `data analysis` (gráficos con conclusiones)

**Enriquecimiento de datos:** Has conseguido enriquecer tu database con web scrapping, esto está perfect!🙌 

**Análisis de datos:** Podrías haber sacado más gráficos mezclando las dos database, pero ya veo que te vas haciendo a los gráficos de pandas!! 💪
