### ISSUE TITLE
[geospatial-data-project] Cristina Arenas Izquierdo

### ISSUE THREAD

**Issue by crisarenas** [ironhack-datalabs/datamad1020#355]
https://github.com/crisarenas/W4-GeoSpatial-Data-Project.git

**Comment by WHYTEWYLL** [comment]
Hola Cris!!! 

Si me lo dejas todo así de bien! Poquito tengo que decirte, capulla 😒  . No pero ahora en serio esta todo SUPER BIEN, de verdad. Si te tuviera que decir algo, esa importación de oficinas en una lista gigante, un poquito fea no? Podrías haber importado el csv, y transfórmalo ahí o impórtalo de otro lado ya transformado etc. Pero así se ve un poco feo. Pero vamos que todo lo demás, organizacion, src... 💯 

FELICIDADES, SIGUE ASI!!

![ae5](https://user-images.githubusercontent.com/49686519/99377040-0821ca80-28c6-11eb-8569-017ea58c3826.jpg)
