### ISSUE TITLE
[geospatial-data-project] Clayton Louden

### ISSUE THREAD

**Issue by WyattGwyon** [ironhack-datalabs/datamad1020#356]
https://github.com/WyattGwyon/geoJSON-data-project

**Comment by adrianacoca** [comment]
Buenos días Clayton!

Enhorabuena!! 🚀 🚀  Sé que tuviste momentos un poco frustrantes a lo largo del proyecto, no obstante te las has apañado y has solucionado todo con debugging! 💪 
Para el siguiente proyecto procura organizar un poco más los archivos con carpetas (por ejemplo una carpeta para imágenes). Has creado funciones suuper útiles (como por ejemplo la función que te devuelve la latitud y longitud de una dirección),  podrías haber creado las funciones en otros archivos e importarlas al jupyter. 

**README:** El readme explica super bien el proyecto! La manera en la que has documentado los jupyters está suuuper bien, se entiende lo que estás haciendo / lo que has intentado hacer en el pasado super claro! 👍  (y me encantan las imágenes que has puesto 😄 )

**Selección de país y ciudad:** Super! La base de datos tenía muchas mas compañías en US, por lo tanto tiene mucho sentido que hayas elegido este país. Has echado un vistazo a aquellas compañías que sean startups y has seleccionado los Angeles con un criterio por detrás 🙌 

**Cumplimiento de requisitos:**  Has sabido pelearte con la api de google para sacar la información que necesitabas para requisitos que has elegido ✅ . No he conseguido ver tu mapa porque no me deja hacer `Trust` del jupyter, por el código tiene pinta de que está perfect. Si quieres mándamelo por Slack cuando tengas un minuto y así le echo un vistazo! (También lo puedes poner en el README)
