### ISSUE TITLE
[geospatial-data-project] Adrian Madrid

### ISSUE THREAD

**Issue by Adrian96119** [ironhack-datalabs/datamad1020#357]
https://github.com/Adrian96119/Mini-proyect-geo.git

Buenas noches, ante todo decir que se que no era lo que se pedia en el proyecto pero me di cuenta tarde para querer cambiarlo, 
asique decidí acabarlo dignamente de esa manera y tirar para adelante, mejor eso que nada!!! jeje

Por cierto quise añadir el link de la api de google y la imagen del mapa y no me cargaba no se porque.

Tambien tuve muchos problemas para importar todos los modulos de pymongo, folium en el anaconda, finalmente
lo resolvi algo tarde, pero lo hice. Ya no me vuelve a pasar más que es lo bueno

**Comment by adrianacoca** [comment]
Buenos días Adrian!!

Sé que tuviste un malentendido en cuanto qué había que hacer para este proyecto, pero te ha faltado un poco mas de tiempo 😞 

Te comento un pare de cosas, en cuanto a la organizaciónara el siguiente proyecto procura organizar un poco más los archivos con carpetas (por ejemplo una carpeta para los archivos que contienen funciones). 

**README:** Veo que has retocado bastante el readme desde ayer y está mas ordenado! 👍  No se si te acuerdas del readme de Angela, pero creo que esa es una manera de explicar el proyecto super clara, procura seguir una estructura más clara y menos textos enteros en mayusculas. Me gusta ver que has puesto el mapa del resultado final de tu oficina seleccionada 😄 

**Selección de país y ciudad:** No era necesario reducir el limite a 10, ya que estás seleccionando 10 oficinas aleatorias de Seatle aleatoriamente sin un criterio. Podrías haber elegido todas las oficinas de Seatle y partiendo de esta base, filtrar en cuanto a la cercanía de los requisitos. 

**Cumplimiento de requisitos:** Has sabido pelearte con la api de google para sacar la información que necesitabas para requisitos que has elegido ✅ . E incluso la has usado para sacar valoraciones, este planteamiento esta genial, porque no sólo quiere decir que haya colegios cerca, sino que también estás asegurándoles a los empleados una educación muy buena.  Me da un poco de rabia que hayas conseguido sacar información de la API pero luego no has usado esta herramienta para seleccionar la oficina, sino que lo has hecho aleatoriamente. 

Creo que estos problemas se deben al inconveniente del viernes y no pasa nada. Pero porfiii para los futuros proyectos estate suuper atento a la presentación del proyecto del viernes para que no te vuelva a pasar lo mismo 🙏
