### ISSUE TITLE
[geospatial-data-project] Ignacio Ordovás Pascual

### ISSUE THREAD

**Issue by ordovas** [ironhack-datalabs/datamad1020#358]
https://github.com/nachordo/geospatial-data-project

Sorry :grin: 
![image](https://user-images.githubusercontent.com/71646315/99291681-7a4fcc00-2840-11eb-8905-ae7354e11886.png)

**Comment by WHYTEWYLL** [comment]
Hola Nacho!! 😄 

Que tal todo? AHAHHAHA no entendía el sorry, y cuando he abierto el Issue , todo a cobrado sentido xD. Malísimo! 😆 . Vamos con el proyecto, el cual esta muy muy bien. Se nota que hayas buscado esa organización de la que hablábamos, además de por supuesto cumplir con los requisitos de este proyecto.

Cositas a comentarte, las funciones a parte de abstraer son para no tener que repetir código. Si tienes tres funciones las cuales cambian pocos parámetros en ellas, y no las puedes agrupar en una sola. Subdivide esa función en funciones para no repetir infinitamente partes. Lo mismo que en ese main, que me estas haciendo los mismos pasos uno de tras de otro. Somos vagos, hay que buscar la forma de no hacer lo mismo muchas veces.

Por lo demás esta todo muy bien! Sigue así!! 🚀 🚀
