### ISSUE TITLE
[geospatial-data-project] Borja del Rio

### ISSUE THREAD

**Issue by BorjaRio** [ironhack-datalabs/datamad1020#359]
ahiii va! mañana cambio algún scrool infinito que hay!

https://github.com/BorjaRio/Geospatial-Data-Project

![image](https://user-images.githubusercontent.com/70910001/99302514-c48c7980-284f-11eb-92a7-4a69ca8047cf.png)

**Comment by adrianacoca** [comment]
Buenos días Borja!

Enhorabuena!! 🚀 🚀  Has realizado un proyecto bastante completo usando bastantes requisitos. 

Tus archivos están bastante bien organizados (por ejemplo la carpeta para imágenes). Has creado funciones suuper útiles (como por ejemplo la función que te devuelve la latitud y longitud de una dirección) 

**README:** El readme explica muy bien el proyecto! Me gusta ver que le vas cogiendo el cariño y todo. La manera en la que has documentado el jupyter está bien. Me has dejado algunos prints un poco largos 😫 pero buenoo... 

**Selección de país y ciudad:** Has creado una serie de filtros para reducir tu seleccion en cuanto a categorías, ubicación disponible y aquellas que hayan levantado más de un millón. Y lo has justificado mediante datos e incluso un gráfico 👍 

**Cumplimiento de requisitos:** Has sabido pelearte con las apis de google para sacar la información que necesitabas para requisitos que has elegido (que son unos cuantos ✅ ) . Cuando haces las queries, las haces para una localización en concreto, esto está bien, pero para mejorar el proyecto podrías haber creado una función que haga esto y haberle pasado todas las coordenadas del filtro de oficinas que tienes para sacar la query para cada oficina. No he conseguido ver tu mapa porque no me deja hacer Trust del jupyter, por el código tiene pinta de que está perfect. Si quieres mándamelo por Slack cuando tengas un minuto y así le echo un vistazo! 

![descarga (3)](https://user-images.githubusercontent.com/65229646/99384704-1a086b00-28d0-11eb-93f5-3d1f319a8b00.jpeg)
