### ISSUE TITLE
[geospatial-data-project] Angela Gomez

### ISSUE THREAD

**Issue by angelagomezf** [ironhack-datalabs/datamad1020#361]
https://github.com/angelagomezf/geospatial-data-project

**Comment by WHYTEWYLL** [comment]
Hello Hello 😄 ,

Poquito que decirte esta todo ya dicho, durante la corrección esta mañana. Felicitarte y remarcarte como, a pesar de todo has conseguido presentar algo que cumple con los requisitos y aportando una solución. Y eso sea en este ámbito como en cualquier otro, es misión cumplida. No solo de las cosas que te llevas de este bootcamp es a nivel técnico, uno de los objetivos también es que crezcas como persona y gestión no solo de los problemas sino de los comportamiento antes las dificultades. Y con esta semana, te puedo asegurar que has hecho un +1 . Sigue así, levanta la cabeza y a seguir para arriba aunque no sepas por donde.

🚀 🚀 🚀
