### ISSUE TITLE
[geospatial-data-project] Alberto Jiménez

### ISSUE THREAD

**Issue by Albertojd** [ironhack-datalabs/datamad1020#362]
https://github.com/Albertojd/geospatial-data-project

"Sigo siendo incapaz de poner imágenes en el Readme, si mañana me podéis echar una mano os lo agradecería.

**Comment by Albertojd** [comment]
"Sigo siendo incapaz de poner imágenes en el Readme, si mañana me podéis echar una mano os lo agradecería; no obstante os parece el nombre de la imagen usada; están en la carpeta "images"

**Comment by adrianacoca** [comment]
Buenos días Alberto!

Tus archivos están organizados perfectos, con una estructura fácil de entender 🙌  !! 

**README:** El readme explica muy bien el proyecto! Para el próximo procura explicar la intención del proyecto en una pequeña introducción. En cuanto a las imágenes, lo más probable es que las hayas insertado en el readme con paths absolutos y no relativos, échale un vistazo a esto. 

En cuanto a las APIs, has realizado un proyecto bastante completo pero deberías haber usado una técnica que fuese filtrando las oficinas en lugar de elegir una al principio.

**Selección de país y ciudad:** Has seleccionado la oficina de Github sin justificarlo, deberías haber filtrado por ciudad partiendo de los datos que tenías seleccionando una ciudad en la que hay muchas startups/empresas de tech. 

**Cumplimiento de requisitos:** Has sabido pelearte con las apis para sacar la información que necesitabas para requisitos que has elegido (que son unos cuantos ✅ ). Me da un poco de rabia porque te has quedado a medias en el aspecto de filtrar,  haces un request para cada requisito pero lo haces para una localización en concreto, deberías haber ido filtrando. Hay varias maneras de hacer esto, por ejemplo quedarte con las oficinas que estén a x distancia del aeropuerto de la ciudad, las oficinas que tengan más de un starbucks a menos de x metros, etc. Dicho esto, has sacado varios mapas de la información que has sacado están bastante bien 🚀 🚀
