### ISSUE TITLE
[geospatial-data-project] Alejandro Medina

### ISSUE THREAD

**Issue by medinaale91** [ironhack-datalabs/datamad1020#363]
https://github.com/medinaale91/miniproject_4

**Comment by adrianacoca** [comment]
Buenos días Ale!

Enhorabuena!! 🚀 🚀 Has realizado un proyecto que esta genial, muy completo y usando bastantes requisitos. Has usado bastantes funciones y eso está perfecto, la próxima vez procura separarlas en otro archivo e importarlas al jupyter.

**README:** El readme explica bien el proyecto! Me gusta ver que le vas cogiendo el cariño y todo, podías haber incluido el mapa de la oficina elegida o algo por el estilo. 

**Selección de país y ciudad:** Has creado una serie de filtros para reducir tu seleccion en cuanto a categorías, ubicación disponible y aquellas que hayan levantado más de un millón. Y lo has justificado mediante datos e incluso un gráfico 👍

**Cumplimiento de requisitos:** Has sabido pelearte con las apis de google para sacar la información que necesitabas para requisitos que has elegido (que son unos cuantos ✅ ) . Y como ya he dicho antes has sido muy eficiente con las funciones que has creado antes. Has tenido en cuenta la cantidad de requests que podías hacer al día para no pasarte. Me parece muy interesante la manera en la que has hecho el ranking, igual podrías haber optimizado el código mediante una función a la que le pasas la lista de within y el numero que le quieres sumar al ranking. 

Sé que lo que más cuesta es arrancar con el proyecto y organizarte para hacerlo, no obstante creo que  deberías estár orgulloso del proyecto ya que lo has planteado de una manera muy creativa y analítica al mismo tiempo. Sé que con un poco más de tiempo habrías sacado más gráficos y mapas sin problema! 🚀
