### ISSUE TITLE
[geospatial-data-project] BlancadeOchoa

### ISSUE THREAD

**Issue by BlancadeOchoa** [ironhack-datalabs/datamad1020#364]
Hola Juan!

Te adjunto aqui el link:
https://github.com/BlancadeOchoa/W4-GeoSpatial-data-project.git

Hay dos cosas con las que me he quedado un poco chafada y son;
1.  No he sido capaz de hacer correcamente el for loop para solo tener que variar la query y las coordenadas con el uso de fourquare y no entiendo porque... lo he probado miil veces y me salta siempre el mismo error!! te lo he dejado en el documento para ver si me puedes explicar porque es... (esta en el jupyter que se llama: 2_filter_foursquare.ipynb)  

2.  No poderle haber dedicado mas tiempo a folium... parece una herramienta super chula y me ha quedado el mapa super cutre por la falta de tiempo... ademas nose porque mi ordenador no hace capturas de pantalla entonces no he podido poner el mapa final en el read me.

muchas gracias!!!!

**Comment by WHYTEWYLL** [comment]
Hola Blanca!!

Antes de nada felicitarte, por entregar el proyecto. CONSEGUIDO. Bien, además de una forma u otra, has dado una respuesta a esa pregunta o problema planteado el viernes. Que a pesar de la incertidumbre o miedo, lo hemos atravesado y hemos llegado a tierra. (Se que ahora estoy con las analogías de barco, pero que le hago. La esencia de pirata) Y como capitana, la misión esta cumplida. El planeamiento, y la lógica me gusta, esta muy bien.  Cositas a decirte, tomando un poco lo dicho a Angela, la ejecución podría haberse redactado mejor, no repetir tantos trozos de codigo. Verdad? Al final y al acabo estas haciendo lo mismo varias veces, simplemente modificando unos parametros.

- El erros, es porque dentro de esa funcion night no existe, se lo tienes que pasar. En el for, lo usas pero sun LEN un numero no los valores a dentro. Es por eso. Si no lo ves luego le echamos un ojo.

- Cuanto a folium, no te preocupes lo compensamos en algún otro proyecto utilizándolo y listo!!

Entiendo como te sientes, pero no hay necesidad de ello. Si has trabajado, no hay nada mas que decir, mientras haya sudor en la frente, no hay porque chafarse. Solo si no se intenta. La cuestión es darle. Sigue así!! 🚀 🚀 🚀
