### ISSUE TITLE
[geospatial-data-project] Gerardo Vitale

### ISSUE THREAD

**Issue by gerardovitale** [ironhack-datalabs/datamad1020#365]
https://github.com/gerardovitale/geospatial-data-project

**Comment by WHYTEWYLL** [comment]
Hola Gerar!!

Antes de nada felicitarte, proyecto entregado! Ademas eso tanto que nos preocupaba como era la organizacion. Finiquitado, muy bien! Buen trabajo. Y tanto lo gráficos, como las funciones recurso están muy bien. Cumples todos lo objetivos 💯 . El Readme es una barbaridad de bueno. Poquito que decirte Captain, esta todo muy bien.

Sigue asi! 🚀
