### ISSUE TITLE
[geospatial-data-project] Alba Álvaro

### ISSUE THREAD

**Issue by AlbaAlvaro** [ironhack-datalabs/datamad1020#366]
https://github.com/AlbaAlvaro/geospatial-data-project.git

Fue un poco caos al principio que no sabía por donde empezar, pero luego muuy guay!

**Comment by WHYTEWYLL** [comment]
Hola Alba!!! 😄 

FUAH!! Que guay que digas eso, no porque hayas sufrido. Sino porque se trata de eso, gestionar el caos, hacerte cargo y conseguir resultados! Además has ido tu solita en el cohete, nada que decirte, TOP! En cuanto al proyecto, las organización esta de 10, y readme muy bien. Cositas a comentarte, las funciones podríamos separarlas en otro archivo .py y exportar este archivo, para asi que quede mucho mas limpio , no? Por otro lado,  hay parte de tu codigo que en verdad tiene la misma estructura y repites, eso facilmente puedes convertirlo en una funcion. Poco mas que decirte , me gusta mucho. 

Sigue asi! Cualquier cosa , me dices!! 🚀 🚀 🚀
