### ISSUE TITLE
[geospatial-data-project] Isa Searle Riesgo

### ISSUE THREAD

**Issue by isabel-searle** [ironhack-datalabs/datamad1020#367]
https://github.com/isabel-searle/geospatial-data-project.git

**Comment by adrianacoca** [comment]
Buenos días Isa!!

Como ya te he comentado antes, tu proyecto está suuper bien!! Has realizado un proyecto muy completo usando muchos requisitos. 🚀 🚀 Y tus archivos están perfectamente ordenados 😄 

**README:** El readme explica muy bien el proyecto, quedan muy claros los pasos que has seguido a lo largo del proyecto! Me gusta ver que le vas cogiendo el cariño y todo. Podrías haber incluido una imagen de un mapa con el resultado final. El jupyter también está documentado muy bien 🚀 

**Selección de país y ciudad:** Has usado un criterio muy justificado para elegir Los Angeles y lo has justificado mediante datos e incluso gráficos 👍 Me encanta ver que has puesto en práctica otras cosas que hemos visto a lo largo de la semana como Tableau 🙌 . 

**Cumplimiento de requisitos:** Has sabido pelearte con las apis de google para sacar la información que necesitabas para requisitos que has elegido (que son unos cuantos ✅ ) . Has creado funciones para hacer las requests y como ya te he comentado antes, esto es muy eficiente, sobretodo teniendo en cuenta la cantidad de coordenadas que tienes. Te has quedado suuuper cerca, con un poco más de tiempo lo habrías sacado. Como te dije, podrías haber ido 'deshaciendote' de oficinas mediante el intersection que has hecho dandole un orden de prioridad a los requisitos hasta que sólo te hubiese quedado una.  No obstante, enhorabuena por el proyecto!! 

![descarga (3)](https://user-images.githubusercontent.com/65229646/99391671-cc453000-28da-11eb-9270-bccf866253d3.jpeg)
