### ISSUE TITLE
[geospatial-project] Candela García

### ISSUE THREAD

**Issue by canbot92** [ironhack-datalabs/datamad1020#368]
https://github.com/candelagarciafdez/geospatial-project

**Comment by adrianacoca** [comment]
Buenos días Candela!

Enhorabuena!! 🚀 🚀 Has realizado un proyecto suuuper completo.

Tus archivos están muy bien organizados y la estructura es muy fácil de entender! 

**README:** El readme explica muy bien el proyecto y has incluido muchisimos gráficos y cachitos de código que quedan muy claros! La manera en la que has documentado el jupyter está bien, hay imagenes que no salen y es bastante probable que sea porque has usado el path absoluto en lugar del relativo(ten esto en cuenta para futuros proyectos)

**Selección de país y ciudad:** Has creado una serie de filtros para reducir tu seleccion y lo has justificado mediante datos e incluso un gráfico 👏 

**Cumplimiento de requisitos:** Has sabido pelearte con las apis para sacar la información que necesitabas para requisitos que has elegido (que son unos cuantos ✅ ) . Has tirado por la opción de harvestine que tiene mucha lógica y la verdad es que eres de los pocas a los que se les ha ocurrido usarlo 🙌 Y has sacado la que tenía los requisitos más cerca en distancia. Me habría gustado ver algún mapa con los resultados, pero dicho esto el trabajo está muy bien 🚀
