### ISSUE TITLE
[geospatial-data-project] Edu Oporto

### ISSUE THREAD

**Issue by EduOporto** [ironhack-datalabs/datamad1020#370]
https://github.com/EduOporto/ironhack-projects/tree/main/geospatial-data-project

**Comment by adrianacoca** [comment]
Buenas tardes Edu!

Bueeno como ya te hemos comentado esta mañana, enhorabuena!! 🚀  

La organización del proyecto está perfecta, muy organizada y facil de entender 🙌 

**README:** Se nota que te has currado el readme, se entiende perfectamente el proceso que has seguido para el proyecto ✅ 

**Elección del país / ciudad:** Has escogido Estados Unidos porque has encontrado mucha información útil para filtrar la información. En la base de datos de compañías también hay muchas más compañías en Estados Unidos, por lo tanto lo más probable es que tu búsqueda sea mucho mas precisa 👍 

**Filtrando en base a requisitos:** Te has peleado con las APIs que habíamos sugerido y también te has buscado algunas por tu cuenta, lo cual está fenomenal. Has sido creativo e intentado ir más allá de lo que recomendábamos! También has sabido representar los datos en distintos tipos de mapas, lo cual representaba los filtros de manera muy visual.

Enhorabuena por el proyecto, se nota que le has puesto mucho esfuerzo!! 
Sigue así 😄 

![descarga (3)](https://user-images.githubusercontent.com/65229646/99411053-78931080-28f3-11eb-878e-0bff5a4db3df.jpeg)
