### ISSUE TITLE
[boston_linear_regression] Isa Searle Riesgo

### ISSUE THREAD

**Issue by isabel-searle** [ironhack-datalabs/datamad1020#498]
https://github.com/isabel-searle/boston_linear_regression.git

**Comment by WHYTEWYLL** [comment]
Buenos dias, Isa!! 🤠 

Que tal estamos ? Vamos que este lab de investigación, de trasteo. Cositas a tener en cuenta, que bueno se han comentado en clase, pero te las menciono. El poder usar mas de una única columna para la predicción. Muchas veces mas no es mejor, y poco tampoco lo es. Parte del trabajo es encontrar ese balance perfecto con los datos en esa exploración para conseguir que nuestro modelo consiga la mayor concordancia con la predicción. Aun asi, buen entrenamiento! Atención máxima, que la clase esta increíblemente interesante!

¡Sigue así!

![images](https://user-images.githubusercontent.com/49686519/100335697-90deeb80-2fd5-11eb-90c0-4d2c68d54765.jpg)
