### ISSUE TITLE
[boston_linear_regression] Cristina Arenas Izquierdo

### ISSUE THREAD

**Issue by crisarenas** [ironhack-datalabs/datamad1020#499]
https://github.com/crisarenas/Statistics.git

**Comment by adrianacoca** [comment]
Buenos días Cris!

Tu ejercicio de boston linear regression está muy bien!! 🙌  
También podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) o haber probado cambiando el tamaño del test. 
Buen trabajo! 🚀 

![descarga (10)](https://user-images.githubusercontent.com/65229646/100325271-ad285b80-2fc8-11eb-8e25-85af1904ea52.jpeg)
