### ISSUE TITLE
[boston-linear-regression] Angela Gomez

### ISSUE THREAD

**Issue by angelagomezf** [ironhack-datalabs/datamad1020#500]
https://github.com/angelagomezf/boston_linear_regression

Hola Juan! Tengo una duda... cuando he intentado representar la recta del modelo de predicción, me daba un error en la x con lo de arange, porque la m no tenía la misma longitud por lo visto. He intentado poner len(m) en vez de los parámetros de arange pero me salía una cosa rarísima (he hecho screenshot). Así que en vez de eso, he escogido el segundo elemento del array y así sí me ha salido una recta bien. Vamos que he hecho una cosa rara...

![Screenshot 2020-11-25 at 17 53 37](https://user-images.githubusercontent.com/71897859/100279151-45d9bf80-2f66-11eb-870d-f22824795ba3.png)

**Comment by WHYTEWYLL** [comment]
Helloooou! Gran Duquesa 😄 

Que tal estamos ? Como fue la tarde de ayer con este lab de investigación, de trasteo. En cuanto al error, poquito comentarte que ya he visto que lo has comentado en clase. Good Job! Eso si te dejo una reflexión a tener en cuenta El poder usar mas de una única columna para la predicción. Muchas veces mas no es mejor, y poco tampoco lo es. Parte del trabajo es encontrar ese balance perfecto con los datos en esa exploración para conseguir que nuestro modelo consiga la mayor concordancia con la predicción. Así como la limpieza que hagamos, y las decisiones que tomemos con estos datos. Aun asi, buen entrenamiento! Atención máxima, que la clase esta increíblemente interesante!

¡Sigue así! 🚀 🚀  P.d: cualquier cosita, me dices! 

![images](https://user-images.githubusercontent.com/49686519/100336708-c9cb9000-2fd6-11eb-9ae4-5dd81d6b9664.jpg)
