### ISSUE TITLE
[boston_linear_regression] Ignacio Ordovás Pascual

### ISSUE THREAD

**Issue by ordovas** [ironhack-datalabs/datamad1020#501]
https://github.com/nachordo/boston_linear_regression.git

![image](https://user-images.githubusercontent.com/71646315/100280472-876b6a00-2f68-11eb-996b-dbef5a07feed.png)

**Comment by adrianacoca** [comment]
Buenos días Nacho!

Tu ejercicio de boston linear regression está muy bien!! 🙌  
Veo que has investigado las correlaciones con muchísimo detalle. ✅ 
A la  hora de hacer el train, test es importante que utilices `sklearn.model_selection.train_test_split` ya que esto seleccionara una proporción de datos seleccionados aleatoriamente en lugar de seleccionar los últimos (así puedes entrenar el modelo de manera menos 'biased') 
También podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) o haber probado cambiando el tamaño del test. 
Buen trabajo! 🚀 

![descarga (10)](https://user-images.githubusercontent.com/65229646/100325271-ad285b80-2fc8-11eb-8e25-85af1904ea52.jpeg)
