### ISSUE TITLE
[boston-linear-regresion] Borja del Rio

### ISSUE THREAD

**Issue by BorjaRio** [ironhack-datalabs/datamad1020#502]
done! 
https://github.com/BorjaRio/boston_linear_regression/blob/master/.ipynb_checkpoints/boston_housing-checkpoint.ipynb

**Comment by WHYTEWYLL** [comment]
Buenos días Borja!

Tu ejercicio de boston linear regression está muy bien!! 🙌
Cositas a comentarte, aunque poco ya que se han resulto gran parte en dudas de clase. Cositas a tener en cuenta podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) o haber probado cambiando el tamaño del test, junto al haber elegido x columnas en funcion de correlacion. En nuestro caso, este tipo de trabajos muchas veces, se trata mas de buscar una balance adecuado. Que nos permite obtener esa aproximación mas a adecuada a la predicción. Pero poquito que comentar. Atención máxima, que la clase esta increíblemente interesante!

Buen trabajo! 🚀
![images](https://user-images.githubusercontent.com/49686519/100337150-5413f400-2fd7-11eb-863b-6d498b1d6ec7.jpg)
