### ISSUE TITLE
[boston-linear-regression] Alberto Jiménez

### ISSUE THREAD

**Issue by Albertojd** [ironhack-datalabs/datamad1020#503]
https://github.com/Albertojd/boston_linear_regression

**Comment by adrianacoca** [comment]
Buenos días Alberto!

Tu ejercicio de boston linear regression está muy bien!! 🙌  
A la  hora de hacer el train, test era posible utilizar más de dos columnas. Al incluir más datos (teniendo en cuenta qué columnas tienen una correlación con prices) tu modelo será más preciso.
También podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) o haber probado cambiando el tamaño del test. 
Buen trabajo! 🚀 

![descarga (10)](https://user-images.githubusercontent.com/65229646/100325271-ad285b80-2fc8-11eb-8e25-85af1904ea52.jpeg)
