### ISSUE TITLE
[boston-linear-regression] Candela García

### ISSUE THREAD

**Issue by canbot92** [ironhack-datalabs/datamad1020#504]
https://github.com/candelagarciafdez/boston_linear_regression

**Comment by WHYTEWYLL** [comment]
Buenos días Candee!

Tu ejercicio de boston linear regression está SUPEER BIEN!! 🙌
Poco que decirte, además se ha visto en dudas gran parte, donde se ha explicado la gran importancia de saber que seleccionar y bueno que tener en cuenta en esa exploración. Con el claro objetico de que nuestro modelo, consegia el menos error posible. Entre otras cositas a probar podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) o haber probado cambiando el tamaño del test.

Sigue asi! 🚀
![images](https://user-images.githubusercontent.com/49686519/100338874-6ee76800-2fd9-11eb-9a33-a3ef144d1fbf.jpg)
