### ISSUE TITLE
[boston-linear-regression] Adrian Madrid

### ISSUE THREAD

**Issue by Adrian96119** [ironhack-datalabs/datamad1020#505]
https://github.com/Adrian96119/boston_linear_regression.git

**Comment by adrianacoca** [comment]
Buenos días Adri!

Tu ejercicio de boston linear regression está muy bien!! 🙌  
Como bien dices, podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) o haber probado cambiando el tamaño del test. 
Buen trabajo! 🚀 

![descarga (10)](https://user-images.githubusercontent.com/65229646/100325271-ad285b80-2fc8-11eb-8e25-85af1904ea52.jpeg)
