### ISSUE TITLE
[boston-linear-regression] Alejandro Medina

### ISSUE THREAD

**Issue by medinaale91** [ironhack-datalabs/datamad1020#506]
https://github.com/medinaale91/boston_linear_regression

**Comment by adrianacoca** [comment]
Buenos días Ale!

Tu ejercicio de boston linear regression está muy bien!! 🙌  
Has dividido los datos para `train` y `test`
Has usado `train` para entrenar el modelo Linear Regression
Has predicho los datos del `test` usando el modelo entrenado previamente
Hasta aquí lo tienes todo perfecto. Si te sigues viendo perdido en cuanto a este ejercicio después del repaso de Felipe escríbeme y lo miramos de nuevo porfa!
Más adelante, podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) o haber probado cambiando el tamaño del test y comparar el rmse para cada uno de los cambios. 

Buen trabajo! 🚀 

![descarga (10)](https://user-images.githubusercontent.com/65229646/100325271-ad285b80-2fc8-11eb-8e25-85af1904ea52.jpeg)
