### ISSUE TITLE
[boston-linear-regression] BlancadeOchoa

### ISSUE THREAD

**Issue by BlancadeOchoa** [ironhack-datalabs/datamad1020#507]
Hola Adri!!

Ayer contigo me quedo mucho mas claro algunos de los conceptos que explico felipe, pero haciendo este lab me han surgido muchas mas dudas en relacion a los ejercicios y porque se toman ciertas decisiones en los pasos que vamos siguiendo.

Las tengo todas apuntadas, nose si quieres que te las ponga aqui, o si prefieres que te las pregunte mañana por la tarde cuando estemos en el breakout room porque son bastante especificas... lo que tu me digas.

Muchsisimas gracias!

https://github.com/BlancadeOchoa/boston_linear_regression.git

**Comment by adrianacoca** [comment]
Buenos días Blanca!

La verdad es que tu ejercicio de boston linear regression está muy bien!! 🙌  
Más adelante, podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) y comparar el rmse para cada uno de los cambios cómo hiciste con el tamaño de los tests. 
En cuanto a las dudas, aprovecha para preguntarlas hoy cuando Felipe repase el ejercicio. Claro que si te sigue quedando alguna duda, lo vemos esta tarde en la breakout! 😄 

Buen trabajo! 🚀 

![descarga (10)](https://user-images.githubusercontent.com/65229646/100325271-ad285b80-2fc8-11eb-8e25-85af1904ea52.jpeg)
