### ISSUE TITLE
[boston-linear-regression] Edu Oporto

### ISSUE THREAD

**Issue by EduOporto** [ironhack-datalabs/datamad1020#508]
https://github.com/EduOporto/boston_linear_regression

**Comment by WHYTEWYLL** [comment]
Buenos días Eduuu! Mi duque!

Tu ejercicio de boston linear regression está SUPEER BIEN!! 🙌
Poco que decirte, además se ha visto en dudas gran parte, donde se ha explicado la gran importancia de saber que seleccionar y bueno que tener en cuenta en esa exploración. Con el claro objetico de que nuestro modelo, conseguir el menos error posible. Entre otras cositas a probar podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) , modificaciones en los test,  X etc

Sigue asi! 🚀

![My Post](https://user-images.githubusercontent.com/49686519/100339728-88d57a80-2fda-11eb-9ea0-dd8801faa701.png)
