### ISSUE TITLE
[boston-linear-regression] Alba Álvaro

### ISSUE THREAD

**Issue by AlbaAlvaro** [ironhack-datalabs/datamad1020#509]
https://github.com/AlbaAlvaro/boston_linear_regression.git

**Comment by WHYTEWYLL** [comment]
Hello! 😄 

Como fue este lab? Un lab de investigación mas bien, no? De prueba, y de practica con nuestros modelos, creo que te has peleado bien, y eso es lo que buscábamos. Como se ha comentado en clase, poquito que decirte. Si comentarte, una pequeña reflexión. Muchas veces, dedicaremos mas tiempo tratando esos datos X para encontrar la mejor configuración posible, con la exploracion, correlacion... Probando diferentes tipos de modelos...  Buen trabajo!

Sigue asi! 🚀 🚀 

![images](https://user-images.githubusercontent.com/49686519/100341034-575dae80-2fdc-11eb-8160-f177b2350916.jpg)
