### ISSUE TITLE
[boston-linear-regression] Clayton Louden

### ISSUE THREAD

**Issue by WyattGwyon** [ironhack-datalabs/datamad1020#511]
https://github.com/WyattGwyon/boston_linear_regression

**Comment by adrianacoca** [comment]
Buenos días Clayton!

La verdad es que tu ejercicio de boston linear regression está muy bien!!
Veo que has logrado separar los datos, entrenar el modelo y sacar predicciones 🙌  
Más adelante, podrías haber probado diferentes modelos (como por ejemplo alguno de statsmodels) o haber cambiado el tamaño del test y comparar el rmse para cada uno de los cambios. 

Buen trabajo! 🚀 

![descarga (10)](https://user-images.githubusercontent.com/65229646/100325271-ad285b80-2fc8-11eb-8e25-85af1904ea52.jpeg)
