### ISSUE TITLE
[boston-linear-regression] Gonzalo Arroyo

### ISSUE THREAD

**Issue by Gon41** [ironhack-datalabs/datamad1020#512]
Buenas,

lo estuve intentando de verás, pero se me hizo muchísima bola y mucho lio, llegó un punto que ya no sabia ni que estaba haciendo...

Link:

https://github.com/Gon41/boston_linear_regression

**Comment by WHYTEWYLL** [comment]
Hola Gon!!

No te preocupes, este lab esta para eso! Para probar, investigar , que se haga bola... Además con las dudas resueltas en clase espero que haya desparecido. Poquito que comentar, porque se ha visto ya de pe a pa. De todos modos, bien peleado. Buen trabajo!  La importancia, del tratamiento, la … De cara a esa aplicacion de modelos, con el objetivo de reducir ese error en la mayor proporción posible.

Sigue asi!! 🚀 
![images](https://user-images.githubusercontent.com/49686519/100341271-a1469480-2fdc-11eb-9e97-ad4c9204fb3c.jpg)
