### ISSUE TITLE
[chat-api] Ignacio Ordovás Pascual

### ISSUE THREAD

**Issue by ordovas** [ironhack-datalabs/datamad1020#513]
https://github.com/nachordo/chat-api.git

![image](https://user-images.githubusercontent.com/71646315/100643966-00890980-333b-11eb-8571-3ca61b949ddc.png)

**Comment by adrianacoca** [comment]
Buenas tardes Nacho!

Veo has conseguido crear una API y meterle información a una base de datos a través de esta, enhorabuena! 🚀 🚀

La presentación y organización de los proyectos es súper importante. Tu README está super bien y tus archivos están muy bien organizados y comentados!!👌

En cuanto a la API que has creado:

- Has creado todos los endpoints que exigía el readme 🙌 
- Has usado programación defensiva para asegurarte de que el usuario que esté usando la API vea lo que está haciendo mal, esto es muy profesional ✅ 
- Has ido mas allá con el análisis de sentimientos sacando los sentimientos tanto por mensaje como por usuario incluso sacando gráficos  🚀 (los cuales he visto en result query - igual podrías haber incluido alguno en el readme)
Enhorabuena por el proyecto, está perfecto!
Buen trabajo 👍

Desde luego que...
![Flask](https://user-images.githubusercontent.com/65229646/100755487-8749ef00-33ec-11eb-8c6d-920408e76750.jpeg)
