### ISSUE TITLE
[chat-api] Borja del Rio

### ISSUE THREAD

**Issue by BorjaRio** [ironhack-datalabs/datamad1020#514]
https://github.com/BorjaRio/Chat-Api

**Comment by WHYTEWYLL** [comment]
Hola Borja! 🤠 

Vamos con esa API! Cositas que comentarte!

- Me gusta la disposición de las carpetas y el uso de ese archivo main.py .  Hoy hemos visto esa importancia de la modularidad, y como estructurar nuestros datos y recursos, para que su uso/ importación sea lo mas sencillo posible.

- Te falta un GITIGNORE como una casa, para que ? Para que por ejemplo esas carpetas .ipynb y _pycache_ no aparezcan que solo hacen mas que ensuciar y nos son necesarias. Son archivos generados por tu pc.

- Muy bien! Consiguiendo, esa conexion con la API de mongo. 💪 

- En cuanto a los endpoints, funcionan. Estan cleans! Y lo conseguiste todo, en esas horas del lunes! Muy buen trabajo! Llegando a ese primeros puntos de los objetivos del trabajo. Eso no quita, para reconocer que el proyecto se ha quedado bastante, bastante excueto. Por no decir translucido. La chicha buena, venia con esos mensajes , y el Sentimental.

- En cuanto al Readme, es la presentación aka la introducción. No me pongas las mismas funciones de tu código, porque para eso ya puedo acceder a los archivos que has subido.

Buen trabajo! Pero, con mas tiempo y metiéndole mas chicha y ganas, yo creo que podrían haber conseguido un trabajo mucho mas completo. Coge buen mindset para esas dos semanas que nos quedan, y vas a conseguir un PROYECTAZO.


![image](https://user-images.githubusercontent.com/49686519/100742297-dab34180-33da-11eb-9577-e09c0d5dffa3.png)
