### ISSUE TITLE
[chat-api] Clayton Louden

### ISSUE THREAD

**Issue by WyattGwyon** [ironhack-datalabs/datamad1020#515]
https://github.com/WyattGwyon/api-chat-project

**Comment by adrianacoca** [comment]
Buenas tardes Clayton!

Me alegra mucho ver que has conseguido crear una API y meterle información a una base de datos a través de esta, enhorabuena! 🚀 🚀 Siento que hayas acabado el lunes por la tarde con tantas dudas, pero la próxima vez no dudes en escribirme para resolverlas desde el minuto uno 🙏 

La presentación y organización de los proyectos es súper importante. Tu README está bastante bien y tus archivos están muy bien organizados!!👌 
 
En cuanto a la API que has creado:
- Has conseguido insertar información a través de requests a la API  🙌  Al insertar los mensajes, podrías haber incluido información como: quién está diciendo este mensaje (es decir el character). Por eso creo que habría sido más adecuado crear un endpoint para cada uso, es decir: Uno para crear un usuario, otro para crear un chat, otro para insertar un mensaje... ya que cada uno sigue una estructura distinta
- Veo que has sacado el análisis de sentimientos a través de NLTK. Has hecho esto directamente en el jupyter notebook y esto no está mal! ✅ Pero podrías haber creado un endpoint para esto y así no tener que repetir el código cada vez que quieras hacer el análisis para un chat. 

Soy consciente de que ayer pasaste un pequeño bache pero habeis tenido muchos días para resolver dudas. Como ya he dicho, no dudes en preguntar antes la próxima vez. Enhorabuena por conseguir tirar hacia delante y sacar este resultado. 🚀 
Buen trabajo 👍  
![Flask](https://user-images.githubusercontent.com/65229646/100722354-d11ce000-33c0-11eb-8af0-a87ad7efcd8a.jpeg)
