### ISSUE TITLE
[chat-api] Gerardo Vitale

### ISSUE THREAD

**Issue by gerardovitale** [ironhack-datalabs/datamad1020#516]
https://github.com/gerardovitale/chat-api

**Comment by WHYTEWYLL** [comment]
Holar Gerar!! 🤠 

Que tal señorito?  De primeras decirte que tu proyecto esta MUY BIEN, FELICIDADES!!! Además , me gusta ver como ya el lunes llegaste con ellos ya simplemente para como decimos nosotros, poner purpurina e incluso yendo mas allá. COMO DEBER SER!! 💪 
Me gusta mucho tu trabajo, la disposición de los archivos esta bastante bien. Se ha notado mucho la mejoría de unos proyectos a otros, como el Readme que esta WOW. He de decirte, alguna cosilla, como por ejemplo -> Cuidado con los path absolutos, tiene que hacer que los programas, funcionen para todos. No solo para tu ordenador, recuerdalo!

He visto, que no te aventuraste al final con el webscrapping para remedir esa falta de permisisos que nos brinda la API de Instagram. Bueno, no lo guardamos en el tintero. Para futuros proyectos! Sigue asi ! 🚀 

![image](https://user-images.githubusercontent.com/49686519/100744431-1d2a4d80-33de-11eb-8fcf-eb25c3d4c553.png)
