### ISSUE TITLE
[chat-api] Cristina Arenas Izquierdo

### ISSUE THREAD

**Issue by crisarenas** [ironhack-datalabs/datamad1020#517]
REPO : https://github.com/crisarenas/W6-chat-API.git

![image](https://user-images.githubusercontent.com/60916297/100681215-8163f780-3373-11eb-8ba3-7d40e1f05244.png)

**Comment by adrianacoca** [comment]
Buenos días Cris!

Has conseguido crear una API y meterle información a una base de datos a través de esta, enhorabuena! 🚀 🚀 

El README está bastante completo, el pantallazo que has incluido ayuda mucho a visualizar las posibilidades de tu api y lo endpoints que hay que usar para cada una 👌 Tus archivos están muy bien organizados y comentados, así da gusto. 

En cuanto a la API que has creado:
- Has creado una api para conectarte con una base de datos 🤩 
- Aunque no hayas 'raised errors', tus funciones si que están devolviendo mensajes cuando el código no es lo esperado, esto está bastante bien y le da profesionalidad al proyecto 🙌
- También veo que has sido capaz de pasarle una lista de nombres a tu función de create chat y extraer sus ids al igual que para crear mensajes, perfecto! ✅ 
- Has intentado extraer el análisis de sentimientos para los mensajes de cada chat y calcular las medias mediante el endpoint `/chat/sentiment`👍  

Enhorabuena por el proyecto, esta muy muy bien
Buen trabajo, sigue asi 🚀 🚀 
![Flask](https://user-images.githubusercontent.com/65229646/100722354-d11ce000-33c0-11eb-8af0-a87ad7efcd8a.jpeg)
