### ISSUE TITLE
[chat-api] Angela Gomez

### ISSUE THREAD

**Issue by angelagomezf** [ironhack-datalabs/datamad1020#518]
https://github.com/angelagomezf/chat-api

**Comment by angelagomezf** [comment]
![Wait-Wait-Thats-Not-Funny-At-All-zt520-550x298](https://user-images.githubusercontent.com/71897859/100681788-d18f8980-3374-11eb-80e7-bfcf89c85965.jpg)

**Comment by WHYTEWYLL** [comment]
Hello Hello!! 🤠 

Que tal Duquesa? 😄  Yo estoy basante contengo, he de decirte e incluso orgulloso me atreveria decir. Te voy a decir porque, lo primero es porque el Readme te ha quedado espectacular, la organización de los archivos esta de 10, además ese gitingore para evitar ahi esos archivos/carpetas que no queremos perfe 😉 . Has conseguido la conexión con Mongo, un Jupyter super clean que se nota que has entendido que es cada cosa, que es un endpoint, cual es la diferencia entre param o variable como endpoint etc Pero sobre todo, porque a pesar de que te has quedado a nada, de conseguir sacar esos mensajes. 
Has ido mas allá, y has dicho, voy  a probar que se utilizar ese nltk, y lo entiendo 💪 . Y te has quedo SUUUPER cerquita, y además se ve que lo has entendido todo lo que estabas haciendo y que a pesar de no haber conseguido sacar esos mensajes de vuelta. Sabias cuales eran los siguientes pasos. Y sin mencionar que tires, de esa INCREIBLE PELICULA. Que es una de mis favoritas, y quieras o no te sube decimillas de la nota inexistente que hay, es SUPER TOP ejjeje

Con un poquito mas de tiempo, te hubiera quedado de 10. Si sigues con esa actitud, aprietas el culo, te va a quedar un proyecto final, MUY GUAY. Muy buen trabajo! Sigue así! 🚀 

![image](https://user-images.githubusercontent.com/49686519/100745594-ce7db300-33df-11eb-8bac-8eb388f7ca02.png)
