### ISSUE TITLE
[chat-api] Edu Oporto

### ISSUE THREAD

**Issue by EduOporto** [ironhack-datalabs/datamad1020#519]
https://github.com/EduOporto/ironhack-projects/tree/main/chat-api

Ahí te va la vaina. Al final no me ha dado tiempo a investigar lo de separar los endpoints, se que me ha quedado un archivo bastante tocho, pero me he enmarronado con otra cosa que me ha tenido un par de horas jodido, así de la nada. 

A la hora de meter las funciones en [esta carpeta](https://github.com/EduOporto/ironhack-projects/tree/main/chat-api/api/chat_api_libs) a parte se me ha jodido la llamada a las funciones de [sql_caller.py](https://github.com/EduOporto/ironhack-projects/blob/main/chat-api/api/chat_api_libs/sql_caller.py) en el archivo [database_filler.ipynb](https://github.com/EduOporto/ironhack-projects/blob/main/chat-api/database_filler.ipynb), que se supone que es el jupyter que rellena la base de datos con randoms. Lo raro es que ese mismo código en [database_filler.py](https://github.com/EduOporto/ironhack-projects/blob/main/chat-api/database_filler.py) sí que tira. Si no te lía mucho a ver si me puedes decir qué coj***s pasa ahí.

Me hubiese gustado poner esos dos archivos filler en una carpeta a parte, pero a la hora de llamar a las funciones que tengo almacenadas en la otra carpeta no me las pilla. He investigado un poco el tema __init__.py y demás, pero ya me ha pillado el toro.

A pesar de todo bastante contento con el resultado, creo que la API tiene bastantes funciones, y se defiende bastante bien ante posibles fallos que el usuario pueda tener (usuario con mismo nickname, añadir dos veces al mismo user a un grupo, etc).

**Comment by WHYTEWYLL** [comment]
Hola Edu! 🤠 

Poquito que decir, esta SUUPER BIEN. El  problemilla ese ya hemos visto que es cuestion de tu Jupyter otro dia le podemos echar un ojo a ver, pero en si funciona y esta muy bien. Las cositas a comentar para ir a por esa cima de la perfección, ya sabes lo que hemos dicho, gestion de archivos, modularidad, hacer esfuerzos para no repetir cosas, comentarios de que hace codigo. Y poquito mas. Sigue asi!! 🚀 🚀  No queda nada! Todo dicho! 💪  

![image](https://user-images.githubusercontent.com/49686519/100763746-e06a5080-33f5-11eb-8365-3770f5dec14a.png)
