### ISSUE TITLE
[chat-api] Carlos Vila-San Juan

### ISSUE THREAD

**Issue by carlosvilasanjuan** [ironhack-datalabs/datamad1020#520]
**link:**
https://github.com/carlosvilasanjuan/chat_api.git

**Comment by adrianacoca** [comment]
Buenas tardes Carlos!

Has conseguido crear una API y meterle información a una base de datos a través de esta, enhorabuena! 🚀 🚀 

El README está un poco flojillo, trabajalo más en futuros proyectos, pero tus archivos están muy bien organizados 👌

En cuanto a la API que has creado:
- Has creado todos los endpoints que pedía el readme de manera organizada y veo que has conseguido meter los datos 🙌
- Has utilizado NLTK en el jupyter y veo que has sacado los resultados y hecho gráficos con ellos✅ Podrías haber incluido este código como un endpoint de la API para sacar estos resultados a través de la API en lugar de a través de Jupyter.

Enhorabuena por el proyecto, esta muy completo 👍  
Buen trabajo, sigue asi 🚀 🚀 
![Flask](https://user-images.githubusercontent.com/65229646/100722354-d11ce000-33c0-11eb-8af0-a87ad7efcd8a.jpeg)
