### ISSUE TITLE
[chat-api] Alejandro Medina

### ISSUE THREAD

**Issue by medinaale91** [ironhack-datalabs/datamad1020#521]
https://github.com/medinaale91/miniproject_week6

**Comment by adrianacoca** [comment]
Buenos días Ale!

Has conseguido crear una API y meterle información a una base de datos a través de esta, enhorabuena! 🚀 🚀 

El README está bastante completo. (Apartados que podrías añadir en futuros README: errores que te has encontrado, posibles cambios o futuro desarrollo si hubieras tenido más tiempo) El esquema de SQL es muy útil para entender la organización de tu base de datos. 

Como hemos comentado antes, tu proyecto está bastante bien ordenado y comentado. 
En cuanto a la API que has creado:
- Has creado una api para conectarte con una base de datos 🤩 
- Has metido información en una base de datos SQL ✅ 
- Has conseguido extraer el análisis de sentimientos para aquellos mensajes 👍 
- Has usado programación defensiva para dejar el proyecto más profesional 🙌 

No me queda nada más que comentar que no hayamos mencionado esta mañana
Buen trabajo, sigue asi 🚀 🚀 
![Flask](https://user-images.githubusercontent.com/65229646/100722354-d11ce000-33c0-11eb-8af0-a87ad7efcd8a.jpeg)
