### ISSUE TITLE
[chat-api] Alba Álvaro

### ISSUE THREAD

**Issue by AlbaAlvaro** [ironhack-datalabs/datamad1020#522]
https://github.com/AlbaAlvaro/chat-api.git

Me han faltado algunas cositas pero lo he hecho lo mejor que he podido :)

**Comment by WHYTEWYLL** [comment]
Hola Alba! 🤠 

Que tal estas? Eso que dices ahí es lo importante -> Dar lo máximo que tengamos! Te comento cosillas vale? Primero, felicitarte! Has cumplido con la gran mayoría de los objetivos marcados, de una forma u otra 👍 . El gitignore es mejor que lo subas al nivel del main, y te explico porque, de esta forma consigues ignorar todo elemento de cualquier nivel por debajo del mismo, y así poder ignorar por ejemplo ese pycache. Por otro lado, Readme, cumplido. Pero , para el futuro podemos intentar añadir alguna imagen, o hacerlo un poco mas atractivo, con conclusión , next steps ...

Temas de seguridad, programación defensiva imagino que habrán sido temas que habrás tenido en cuenta pero por falta de tiempo, no habrás hecho, pero para siguientes veces! Por el resto, todo bastante bien! Conexión con mongo, inserción de datos, endpoints , y sentiment. 💪  A darlo todo, y te va a quedar un proyecto final increíble, que contaras con mas tiempo. Sigue así!! 🚀 

![image](https://user-images.githubusercontent.com/49686519/100760329-f118c780-33f1-11eb-85ae-d0d6fd3b2047.png)
