### ISSUE TITLE
[chat-api] Adrian Madrid

### ISSUE THREAD

**Issue by Adrian96119** [ironhack-datalabs/datamad1020#523]
https://github.com/Adrian96119/Mini-proyect-API-de-chat.git

bueno solo comentarte un par de cositas, 
primero: el readme me ha salido de otra manera de como lo había puesto en mi notebook, se puso como le dio la gana no me mates xfavor :P, nose porque habrá sido con lo bien que lo tenía...
segundo: bueno veras que hay una carpeta que pone cache, no la he borrado por lo que pueda ser pero vamos la chicha esta
en main, y que otra cosa de las que no pude resolver era separar las cosas, como que solo podía manejar mi aplicación desde un archivo y demás aunque lo importara a otro y lo tuve que dejar así
y tercero, la verdad que la api solo me funciona con el visual abierto y habiéndola ejecutado después con el flask run, no se si es
muy normal o no la verdad, quizá sea una tontearía pero quisiera saberlo, GRACIASSSSSSSSSSS :pPPPPP

**Comment by adrianacoca** [comment]
Buenos días Adri!

Primero de todo, enhorabuena por el proyecto! 🚀 🚀 

Que pena lo del README 😢 Si quieres luego lo miramos para ver cómo solucionarlo, pero me gusta ver que te los has trabajado! Como hemos comentado antes, habría estado bien que hubieses separado tu proyecto en distintos ficheros para que estuviese más organizado. (Habiendo importado la instancia de un fichero a otro) 

En cuanto a la API que has creado, has conseguido realizar todos los requisitos que pedíamos ✅ 
Has usado programación defensiva para dejar el proyecto más profesional 🙌 
Te las has arreglado tu solo para codificar contraseñas 👍 

No tengo mucho más que añadir a lo que te hemos comentado antes 😄 
Buen trabajo, sigue asi 🚀 🚀 
![Flask](https://user-images.githubusercontent.com/65229646/100722354-d11ce000-33c0-11eb-8af0-a87ad7efcd8a.jpeg)
