### ISSUE TITLE
[chat-api] BlancadeOchoa

### ISSUE THREAD

**Issue by BlancadeOchoa** [ironhack-datalabs/datamad1020#524]
Hola Adri!
Estoy contenta con el resultado aunque se que hay mucho donde se podria mejorar.
- Podria haberle pasado mas parametros a los endpoints en forma de lista, usando un database de kaggle o extrayendo info de slack como nos enseño juan
- Además, el endpoint del sentiment no lo he hecho bien, he creado directamente un nuevo jupyter donde lo he analizado ahi independientemente porque no sabia como incorporarlo en una query.

Muchas gracias!
https://github.com/BlancadeOchoa/W6-Chat-API.git

**Comment by adrianacoca** [comment]
Buenas tardes Blanca!

Has conseguido crear una API y meterle información a una base de datos a través de esta, enhorabuena! 🚀 🚀 

 La presentación y organización de los proyectos es súper importante y tu README está muy currado tus archivos están muy bien organizados!!👌

En cuanto a la API que has creado:
- Veo que has creado todos los endpoints que se pedían 🙌
- Has conseguido insertar toda la información a través de requests en jupyter ✔️ 
- Veo que has sacado el análisis de sentimientos a través de NLTK. Has hecho esto directamente en el jupyter notebook y esto no está mal! ✅ Pero podrías haber creado un endpoint para esto y así no tener que repetir el código cada vez que quieras hacer el análisis para un chat. 

Enhorabuena por el proyecto, esta muy completo 👍  
Buen trabajo, sigue asi 🚀 🚀 
![Flask](https://user-images.githubusercontent.com/65229646/100722354-d11ce000-33c0-11eb-8af0-a87ad7efcd8a.jpeg)
