### ISSUE TITLE
[chat-api] Alberto Jiménez

### ISSUE THREAD

**Issue by Albertojd** [ironhack-datalabs/datamad1020#525]
https://github.com/Albertojd/Chat-API

Sin que suene a llanto... no he podido añadir mensajes, y por consiguiente no he podido analizarlos con NLP.
No he parado de recibir fallos, la constante del proyectos ha sido, desinstalar librerías, volverlas a instalar, solucionar conexiones con la base de datos y eso me ha lastrado mucho.
No estoy nada orgulloso con el resultado del proyecto, no me ha salido nada de lo que quería.
Volveré a él cuando reinstale sistema operativo y reinstale todos los programas de nuevo, a ver si puedo hacerlo de otra manera.

**Comment by adrianacoca** [comment]
Buenos días Alberto!

Bueeno como ya te hemos comentado antes, no te lamentes tanto por tu trabajo. 
Has conseguido crear una API y meterle información a una base de datos a través de esta, enhorabuena! 🚀 🚀 

El README es muy importante para tener un github presentable 😢 Trabájalo un poco está tarde y mañana le volveré a echar un vistazo 🙏 

Como hemos comentado antes, habría estado bien que hubieses separado tu proyecto en distintos ficheros para que estuviese más organizado. (Habiendo importado la instancia de un fichero a otro) 
En cuanto a la API que has creado:
Has investigado por tu cuenta con los distintos métodos ✅ 
Has usado programación defensiva para dejar el proyecto más profesional 🙌 
Te las has arreglado tu solo para codificar contraseñas 👍 

No tengo mucho más que añadir a lo que te hemos comentado antes 😄 
Buen trabajo, sigue asi 🚀 🚀 
![Flask](https://user-images.githubusercontent.com/65229646/100722354-d11ce000-33c0-11eb-8af0-a87ad7efcd8a.jpeg)
