### ISSUE TITLE
[api-chat-project] Candela García

### ISSUE THREAD

**Issue by canbot92** [ironhack-datalabs/datamad1020#526]
https://github.com/candelagarciafdez/api-chat-project

**Comment by WHYTEWYLL** [comment]
Hola Cande! 🤠 

Que tal estamos? 😄 
Antes de nada, FELICITARTE! Has cumplido con todos lo puntos del proyecto. Enhorabuena! Cosas importantes, la gestión de archivos , que ya hemos comentado en clase. Esa importancia, del main , endpoints... Buscando esa modularidad. En cuanto al Readme. no me pongas código que para eso ya tengo los archivos de código ejeejjeje . Piensa en el Readme, como la contraportada de un libro, lo necesario para llamar la atención a que entre. Por lo demás , esta todo MUY BIEN! 🚀 🚀 

Sigue asi! Subamos una marcha mas, de cara esta ultima semasnas, que con tiempo y a nada que le metas caña te va a quedar un proyecto final, ESPECTACULAR. 

![image](https://user-images.githubusercontent.com/49686519/100766132-99318f00-33f8-11eb-807b-5261b09fb937.png)
