### ISSUE TITLE
[chat-api] Gonzalo Arroyo

### ISSUE THREAD

**Issue by Gon41** [ironhack-datalabs/datamad1020#527]
https://github.com/Gon41/Chat-API

No mucho más que decir.. no he dado pie con bola

**Comment by WHYTEWYLL** [comment]
Hola Gonzalo! 😄 

Escúchame Gonzalo, no te voy a comentar nada del proyecto porque sabes como esta. Y no voy a decir mas. Quédate, con lo que hablamos, con lo que trabajaste ayer. Y de aquí a delante, esa misma actitud. Céntrate en el día, trabaja y ya habrá tiempo de mirar adelante o atrás. De ahora en adelante, te quiero jugando los 90 min sudando aunque no se marque. Se tarde mas o menos, solo se consigue jugando y sufriéndolo. Te recomiendo que cojas, hoy después del lab, y vayas uno por uno echando vistazo al los proyectos de tus compañeros. Con el readme al aldo, y vayas sacando todo. Y lo que no entiendas, te lo apuntes y cuando haya tiempo te lo trates de hacer ejemplos simples tu, y cuando algo tras haberlo trabajado no lo entiendas o no se de.  Me preguntes. Ya veras que si haces esto, avanzaras. Trust me!  . 🚀  Esfuerzo diario
