### ISSUE TITLE
[chat-api] Isa Searle Riesgo

### ISSUE THREAD

**Issue by isabel-searle** [ironhack-datalabs/datamad1020#528]
https://github.com/isabel-searle/chat-api.git
Perdona tenía en mente que había hecho la issue el mismo viernes (para no olvidarme).
los archivos que tienen un commit "I commit some unnecesary data for the project" los he añadido ahora para trackearlos pero no son necesarios para el proyecto.

**Comment by WHYTEWYLL** [comment]
Hola Isa! 😄 

Que tal estas? Vamos con esa corrección de proyecto, pero ya te adelanto que está MUY BIEN. 🚀 
Cositas que te voy a comentar:

- Genial ese Gitignore. Muy buen trabajo! pero si utilizamos el " * " nos va a pillar todos lo que se llamen de esa forma, lo digo por esas carpetillas pycache que están dentro de otras.

- La organización, le falta reposar un poquito mas. Mucho archivo veo, prueba a utilizar una carpeta src (source) para meter todos esas funciones o archivos py que son recursos de otros. Output para esos resultas y asi. Buscamos que quede lo mas limpito posible, el main y carpetas

- Readme! 👍 

- En cuanto a las funciones, en general estan bastante bien. Pero hay veces que aunque sean 2 lineas, las repites como en add-data. Podemos hacer una función que haga ese paso y simplemente llamarlo.

Pero pooquito mas que decirte, MUY BUEN trabajo. Están todo lo objetivos , CUMPLIDISIMOS. Muy buen trabajo Isa! 

![image](https://user-images.githubusercontent.com/49686519/100856164-5bca1180-348b-11eb-84e9-bb9b5e8809f0.png)

¡Sigue así! 🚀 🚀
