### ISSUE TITLE
[diamonds] Isa Searle Riesgo

### ISSUE THREAD

**Issue by isabel-searle** [ironhack-datalabs/datamad1020#594]
https://github.com/isabel-searle/diamonds.git

**Comment by adrianacoca** [comment]
Buenos días Isa! 

Enhorabuena por el concurso!!! 🥳  🥇 

El README está muy bien, se entienden perfectamente los pasos que has seguido en el proyecto y la lógica que hay detrás. Tus archivos están perfectamente organizados también 🙌 

Tu manera de usar funciones para verificar el performance de los modelos es muy eficiente. Te ha permitido probar variaciones de modelos y limpiezas de datos (es decir, qué columnas estás usando)

Entre esto y la presentación está todo dicho, buen trabajo! 🚀
 
![winner](https://user-images.githubusercontent.com/65229646/101332373-7d553f80-3875-11eb-8901-1a176bce5cab.png)
