### ISSUE TITLE
[diamons] Borja del Rio

### ISSUE THREAD

**Issue by BorjaRio** [ironhack-datalabs/datamad1020#595]
https://github.com/BorjaRio/Diamonds

**Comment by adrianacoca** [comment]
Buenos días Borja!  

A ver que tal se ha dado el proyecto, te comento un par de cosas: 

Te ha faltado meterle un poco más de trabajo al README. Podrías haber incluido tu enfoque/s para limpiar los datos (qué columnas vas a usar), tus resultados de cada modelo, maneras que has usado para optimizar los modelos. 
La organización de los archivos no está mal pero te comento: 
 - Tienes un archivo 🚨 `Untitled.ipynb` 🚨
 - Podrías haber agrupado los jupyters de cada modelo en una carpeta

Veo que has investigado un poco los datos y usado algún gráfico (esto puede ser muy útil para entender mejor los datos). Podrías haber hecho la limpieza en otro jupyter y haberlo exportado como csv para no tener que realizar la limpieza en cada jupyter. A la hora de probar cada modelo, habría estado bien que hubieses creado funciones para así poder probar más modelos de manera más optima e incluso haber probado distintas variaciones en cuanto a las columnas que estabas usando para predecir los datos. 
 
Podrías haber intentado sacar un poco más de este proyecto, de todas maneras buen trabajo 🚀 

![Kaggle](https://user-images.githubusercontent.com/65229646/101333586-133d9a00-3877-11eb-9db2-1141ac076abf.jpeg)
