### ISSUE TITLE
[diamonds] Ignacio Ordovás Pascual

### ISSUE THREAD

**Issue by ordovas** [ironhack-datalabs/datamad1020#596]
https://github.com/nachordo/kaggle-competition

![image](https://user-images.githubusercontent.com/71646315/101294645-1c981980-3819-11eb-95bb-f8403860d333.png)

**Comment by WHYTEWYLL** [comment]
Hola Nacho! 😄 

Poquito mas que decirte, tras la presentación en clase. Volverte a decir, FELICIDADES. 
Muy buen trabajo! Espero que sigas agarrado al cohete, y hagas un proyecto final, espectacular!

Sigue así! 🚀 🚀 
 
![image](https://user-images.githubusercontent.com/49686519/101333929-80e9c600-3877-11eb-99fb-3c94ecdeb8e8.png)
