### ISSUE TITLE
[diamonds] Alberto Jiménez

### ISSUE THREAD

**Issue by Albertojd** [ironhack-datalabs/datamad1020#597]
https://github.com/Albertojd/kaggle-competition

**Comment by WHYTEWYLL** [comment]
Hola Alberto! 🤠 

Que tal estamos? Bien presentando hoy, se nota la mejoría de menos lloros jejeje. Bien ahi con el readme , me gusta mucho. Cuidado, como se te ha mencionado, en saber tratar un problema de regresión o de clasificación. En cuanto a lo demás, ya esta dicho en clase, la organización un 💯. Me alegra que de ser tan pesado, se haya hecho. Good Job! Has estado avispado utilizando ese H20 👍 .

Muy buen trabajo!

![image](https://user-images.githubusercontent.com/49686519/101333953-89420100-3877-11eb-82fc-9f379e313bc4.png)
