### ISSUE TITLE
[diamonds-competition] Candela García

### ISSUE THREAD

**Issue by canbot92** [ironhack-datalabs/datamad1020#598]
https://github.com/candelagarciafdez/diamonds-competition

**Comment by adrianacoca** [comment]
Buenos días Candela!  

Bueeno veo que has conseguido un RMSE de **640**, enhorabuena!! 🚀 

Te comento un par de cosas sobre el proyecto: 

Tu README está bastante bien, podrías haber incluido algún detalle más como por ejemplo tus resultados para cada modelo. 
La organización de los archivos está bastante bien 👍  Podrías haber organizado un poco mejor la carpeta de Algunos_modelos (cuidado con las mayusculas en los archivos) separando los jupyters en limpieza y entrenamiento para así no tener que repetir código (ej: cuando modificas las columnas `cut`, `color`, `clarity`)

Veo que has investigado un poco los resultados y usado algún gráfico (esto puede ser muy útil para entenderlo mejor). A la hora de probar cada modelo, habría estado bien que hubieses creado funciones para así poder probar más modelos de manera más optima e incluso haber probado distintas variaciones en cuanto a las columnas que estabas usando para predecir los datos. 
 
Buen trabajo 🚀 
![Kaggle](https://user-images.githubusercontent.com/65229646/101333586-133d9a00-3877-11eb-9db2-1141ac076abf.jpeg)
