### ISSUE TITLE
[diamonds] Alejandro Medina

### ISSUE THREAD

**Issue by medinaale91** [ironhack-datalabs/datamad1020#599]
https://github.com/medinaale91/miniproject_week7

**Comment by WHYTEWYLL** [comment]
Hola Ale! 🤠 

Que tal estamos!? Tengo algunas cositas que comentarte , me gusta como pinta esa organización, y esos diferentes archivos con cada modelo. Pero porque no, utilizar una función que nos ejecute los diferentes modelos, y asi luego quedarnos con aquellos con menor rmse. Y así , podemos tener dos archivos uno de data cleaning y otro de ejecución del modelo x. Hay que buscar, que los archivos que existan tengan un motivo vital. 

Muy buen trabajo! 
![image](https://user-images.githubusercontent.com/49686519/101336347-a7f5c700-387a-11eb-970c-29209bbef833.png)
