### ISSUE TITLE
[diamonds] Carlos Vila-San Juan

### ISSUE THREAD

**Issue by carlosvilasanjuan** [ironhack-datalabs/datamad1020#600]
https://github.com/carlosvilasanjuan/MLcompetition

**Comment by WHYTEWYLL** [comment]
Hola Carlos! 🤠 

Me gusta mucho esa organización, esta BASTANTE bien. Buen trabajo! En cuanto al código, esta bien. Eso si, se repite MUCHO . Porque no, si estas haciendo todo el rato lo mismo, un bucle con un dict, donde vayas cambiando ese modelo utilizado. Para no tener un Júpiter entero, con un casi todo copy paste. Me hubiera gustado, un poco mas de info paso a  paso, para saber el motivo por el que haces cada cosa. Y porque tomas esas decisión, un poco el proceso mental.

Buen trabajo! Sigue así! 🚀 🚀 

https://github.com/WHYTEWYLL/Diamonds-competition
![image](https://user-images.githubusercontent.com/49686519/101337404-e5a71f80-387b-11eb-8576-8f3287c5a108.png)
