### ISSUE TITLE
[diamonds] Edu Oporto

### ISSUE THREAD

**Issue by EduOporto** [ironhack-datalabs/datamad1020#601]
https://github.com/EduOporto/ironhack-projects/tree/main/kaggle-project

Ahí va mi proyecto, al final creo que he conseguido bajar de los 700, no está mal, aunque lejos de los 500 que he visto por ahí. Tuve un mal rato hasta descubrir las regresiones polinomiales, aunque ahora todo tiene sentido. Creo que me ha faltado combinarlas con el modelo correcto, pero lo importante es que he visto el camino y he leído bastante, toca profundizar más en esto.

![](https://e00-elmundo.uecdn.es/television/programacion-tv/img/programas/54/2388.png)

**Comment by adrianacoca** [comment]
Buenos días Edu 

Bueno veo que has conseguido un RMSE de **700**, no está nada mal!! 🚀 

Te comento un par de cosas sobre el proyecto: 

- Tu README está perfecto, se entiende perfectamente. La organización de los archivos está bastante bien también 👍  

- Veo que has probado varios modelos y comparado sus métricas y así has conseguido bajar tu RMSE mediante la prueba y error y esto era de lo que trataba el proyecto. Creo que con un poco más de tiempo y submissions habrías bajado bastante más. 

- Has investigado los resultados usando algún gráfico (esto puede ser muy útil para entenderlo mejor) 🙌 


Una manera de entrenar más modelos habría sido mediante funciones para así poder probar más modelos de manera más optima e incluso haber probado distintas variaciones en cuanto a las columnas que estabas usando para predecir los datos. 
 
Buen trabajo!
![Kaggle](https://user-images.githubusercontent.com/65229646/101333586-133d9a00-3877-11eb-9db2-1141ac076abf.jpeg)
