### ISSUE TITLE
[diamonds] Angela Gomez

### ISSUE THREAD

**Issue by angelagomezf** [ironhack-datalabs/datamad1020#602]
https://github.com/angelagomezf/diamond-competition

**Comment by adrianacoca** [comment]
Buenos días Angela 

A ver tal se ha dado el proyecto: 

- Tu README está muy bien, igual podrías haber incluido las métricas del performance de cada modelo que has entrenado. La organización de los archivos está bastante bien también 👍  

- Veo que has investigado los datos mediante gráficos, esta es una práctica muy buena que puede ser muy útil para entender los datos mejor 🙌 

- En cuanto a la limpieza de datos,  las modificación de las columnas `cut`, `color`, `clarity` está muy bien. Pero podrías haber mantenido las columnas `x`, `y`, `z` y haber probado distintas variaciones en cuanto a las columnas qué estabas usando a ver cómo cambiaban las métricas del RMSE

- Una manera de entrenar más modelos habría sido mediante funciones para así poder probar más modelos de manera más optima.
 
A pesar de estos comentarios, te has currado un montón el proyecto 🚀 
Buen trabajo!
![Kaggle](https://user-images.githubusercontent.com/65229646/101333586-133d9a00-3877-11eb-9db2-1141ac076abf.jpeg)
