### ISSUE TITLE
[diamonds] Adrian Madrid

### ISSUE THREAD

**Issue by Adrian96119** [ironhack-datalabs/datamad1020#603]
https://github.com/Adrian96119/ML-DIAMONDS-PRICES.git

**Comment by Adrian96119** [comment]
No entiendo el ranking  de kaggle, se supone que baje el error y comprobé personalmente que tenia 546, hice la comprobacion igual que en el otro, no se que ha podido pasar

**Comment by WHYTEWYLL** [comment]
Hola Adri!

Lo que me comentas, puede ser por no haber seleccionado, la submission nueva, en vez de las anteriores. 

En cuanto al trabajo, te hago un repaso. En general buen trabajo consiguiendo ese error, bastante bien! Aunque he de decir que el proyecto parece ser de primera semana. Que es esa organizacion? Ese pupurri de archivos, que parece el escritorio de mi madre. Ni un gitignore, para evitar subir esos archivos no deseados, como  pycache. Los nombres de los archivos, mayusculas minusculas espacios whatever . Cosas en ingles , y en español. Uno u otro, ha no ser que sea un anglicismo. Csv por un lado, py por otro y así. Hay que empezar a cuidar un poquito mas lo que hacemos.  Esto ????????????????????????????????

![image](https://user-images.githubusercontent.com/49686519/101338871-dcb74d80-387d-11eb-9e2a-ed997bdf33bf.png)

![image](https://user-images.githubusercontent.com/49686519/101338902-eccf2d00-387d-11eb-9eef-f0f3e22e9443.png)

El control c y control v , bien no? Yo creo que eres mas que capaz de hacer  algo en menos lineas, que consiga sacar ese resultado. Programando un poquito aunque sea,no?

Buen trabajo! 

![image](https://user-images.githubusercontent.com/49686519/101339012-1b4d0800-387e-11eb-9cdd-d36fb1f78809.png)
