### ISSUE TITLE
[diamonds] BlancadeOchoa

### ISSUE THREAD

**Issue by BlancadeOchoa** [ironhack-datalabs/datamad1020#604]
Hola Juan!

Como siempre me hubiese gustado tener mas tiempo que dedicarle al proyecto ya que me ha quedado el codigo SUPER repetitivo porque no me ha dado tiempo a hacer funciones para automatizarlo.

Ademas, no he acabado de conseguir un rmse lo suficientemente bajo.... he probado mil modelos y he limpiado el database de muchas maneras pero nada.... cuando pensaba que porfin habia conseguido un rmse bajo (de 560 segun mi jupyter usando el random forest), en kaggel daba 10.000..... lo cual no acabo de entender porque pasa.... se que es porque debe estar overfitted pero nose como arreglarlo... ya he aumentado el train size y hecho cv pero nada...

muchas gracias!
https://github.com/BlancadeOchoa/W7-diamonds.git

**Comment by WHYTEWYLL** [comment]
Hola Blanca!! 🤠 

Totalmente! Lo que me dices, pero bueno la cuestión es hacer lo máximo que podamos en estos días. Y cuando tengamos tiempo, volver y dejar de 10!  Me gusta bastante esa organización , aunque ese checkpoints, me falta un GITIGNORE como una casa. Hasta que he entrado a resources, y literalmente esta ahi todo los trapos sucios escondido, cual revisión de los padres al cuarto AJAJAJAJJ 🤦  Que es eso? Parece la papelera del ordenador. 
Es mejor si hacemos uso de funciones y puntos py, para correr diferentes modelos, y si quieres enseñar lo que has hecho en diferentes días o porque haces unas cosas y no otras. ESCRIBE , no  hagas try 1 , try2 .... Porque si haces esos con cada cosas que hagas programando, harás 100000 archivos, de todos los intentos que hagas. Explica, justifica y argumentar.

Quitando eso. Buen trabajo!

![image](https://user-images.githubusercontent.com/49686519/101341141-edb58e00-3880-11eb-987f-105533274773.png)
