### ISSUE TITLE
[diamonds] Alba Álvaro

### ISSUE THREAD

**Issue by AlbaAlvaro** [ironhack-datalabs/datamad1020#605]
https://github.com/AlbaAlvaro/kaggle-competition.git

**Comment by adrianacoca** [comment]
Buenos días Alba 

Enhorabuena! Has conseguido un RMSE de **570** 🚀 

Te comento un par de cosas sobre el proyecto: 

- Tu README no está mal, igual podrías haber incluido las métricas del performance de cada modelo que has entrenado o incluso algún gráfico. La organización de los archivos está bastante bien 👍  

- Has probado un montón de modelos y conseguido bajar el RMSE mediante prueba y error leyendo las métricas, que era uno de los principales objetivos del proyecto 

- Una manera de entrenar más modelos habría sido mediante una función a la que le pasabas el modelo y sus parámetros y te devolvía el RMSE para ambos el train y test.
 
Te has currado un montón el proyecto 🚀 
Buen trabajo!
![Kaggle](https://user-images.githubusercontent.com/65229646/101333586-133d9a00-3877-11eb-9db2-1141ac076abf.jpeg)
