### ISSUE TITLE
[diamonds] Cristina Arenas Izquierdo

### ISSUE THREAD

**Issue by crisarenas** [ironhack-datalabs/datamad1020#606]
https://github.com/crisarenas/W7-Diamonds-Competition.git

**Comment by WHYTEWYLL** [comment]
Hola Cris! 🤠 


Que tal estas xula? Tu código esta super bien. Muy buen trabajo. Eso si, echo de menos un gitignore, y que buscases un poco la modularidad, para que en un documento hubieras argumentado que modelo usar, en vez de tener 9 jupyter cada uno con un modelo, utilizando un poquito de código. Lo demás, buen trabajo!

Sigue asi! 🚀 🚀 

![image](https://user-images.githubusercontent.com/49686519/101343343-299e2280-3884-11eb-9d17-c611619f7a39.png)
