### ISSUE TITLE
[diamonds] Clayton Louden

### ISSUE THREAD

**Issue by WyattGwyon** [ironhack-datalabs/datamad1020#607]
https://github.com/WyattGwyon/diamond-price-predictions

**Comment by WHYTEWYLL** [comment]
Hola Clayton!!! 🤠 

Que tal estas!! A pesar de que no hayas conseguido un modelo, con un error aceptable. El trabajo esta SUUUPER BIEN, esta todo muy bien. Me hace ilusion porque se nota, que lo vas pillando! Good Job! 💪  Te recomiendo que cuando puedas, intenta probar con otros modelos. Puedes probar a crear una función, que ejecute varios modelos y asi elegir. Randomforest.. O H2o, pero esta muy bien!

Buen trabajo! Sigue asi!! 🚀 🚀 

![image](https://user-images.githubusercontent.com/49686519/101343695-ae893c00-3884-11eb-9e1e-e2abc59c288d.png)
