### ISSUE TITLE
[diemonds] Gonzalo Arroyo

### ISSUE THREAD

**Issue by Gon41** [ironhack-datalabs/datamad1020#608]
https://github.com/Gon41/-kaggle-competition-

Dejo un temazo:

https://www.youtube.com/watch?v=t9kINGuPAC0&ab_channel=diemonds

**Comment by adrianacoca** [comment]
Buenos días Gonzalo 

Bueno a ver que tal se ha dado el proyecto: 

- Tu README no está mal, podrías haber incluido las métricas del performance de cada modelo que has entrenado o incluso algún gráfico. Podrías haber organizado los archivos mediante carpetas, por ejemplo:
`inputs` - csv iniciales
`outputs` - csv a entregar
`models` - jupyters de los modelos entrenados

- Has probado unos cuantos modelos y conseguido bajar el RMSE, que era uno de los principales objetivos del proyecto. Creo que podrías haber bajado el resultado aún más mediante alterando los parámetros de los modelos y probando excluyendo distintas columnas hasta encontrar la manera más óptima. 

- Una manera de haber entrenado más modelos habría sido mediante una función a la que le pasabas el modelo y sus parámetros y te devolvía el RMSE para ambos el train y test.
 
Te has currado un montón el proyecto 🚀 
Buen trabajo!
![Kaggle](https://user-images.githubusercontent.com/65229646/101333586-133d9a00-3877-11eb-9db2-1141ac076abf.jpeg)
