### ISSUE TITLE
[diamonds] Gerardo Vitale

### ISSUE THREAD

**Issue by gerardovitale** [ironhack-datalabs/datamad1020#609]
https://github.com/gerardovitale/diamond-price-prediction-kaggle

**Comment by adrianacoca** [comment]
Buenos días Gerardo 

Congrats, has conseguido un RMSE de **765** !

Te paso un par de comentarios sobre el proyecto: 

- Podrías haber completado el README un poco mas mostrando los distintos modelos que has usado y explicado su performance mediante métricas o incluso algún gráfico. 

- La organización de tus archivos está bastante bien.

- Veo que has usado varias funciones para entrenar los modelos y esto está muy bien! 🙌  Igual podrías haber hecho una función más general a a la que le pasases el modelo que querías entrenar y los parámetros que querías usar. 

- Has probado unos cuantos modelos y conseguido bajar el RMSE mediante prueba y error leyendo las metricas, que era uno de los principales objetivos del proyecto. Igual podrías haber bajado el resultado aún más mediante alterando los parámetros de los modelos y probando distintas combinaciones de columnas hasta encontrar la manera más óptima. 

Se nota el esfuerzo que has puesto en el proyecto
Buen trabajo!🚀 
![Kaggle](https://user-images.githubusercontent.com/65229646/101333586-133d9a00-3877-11eb-9db2-1141ac076abf.jpeg)
