### ISSUE TITLE
[mini-project] Cristina Arenas Izquierdo

### ISSUE THREAD

**Issue by crisarenas** [ironhack-datalabs/datamad1020#84]
https://github.com/crisarenas/W1-MiniProject-Game.git

**Comment by adrianacoca** [comment]
Hola Cris!

Como ya comentamos en clase, creo que te las has apañado super bien con el proyecto. Cosas que me han gustado especialmente del proyecto: 
 - Poder visualizar las letras que se han probado
 - Revisar si el input es una letra
 - Has importado funciones de otros archivos 🤩 
 - Has hecho el juego más visual con los dibujos del ahorcado

Tu README está bastante completo y es fácil seguir tu código (los comentarios también ayudan)
Enhorabuena!

![images](https://user-images.githubusercontent.com/65229646/97302344-37aa5d80-1859-11eb-8c2b-16096a582795.png)
